// Code generated by generate-pulumi.ts — DO NOT EDIT.

import * as pulumi from "@pulumi/pulumi";
import type { AgentCredential as AgentCredentialData } from "pgbeam";
import { apiErrorStatus, createClient, handleApiError } from "./provider.js";
import { stripUndefined } from "./utils.js";

export interface AgentCredentialArgs {
  /** Owning project ID. */
  projectId: pulumi.Input<string>;
  /** Policy profile enforced for this credential. */
  policyProfileId: pulumi.Input<string>;
  /** Human-readable label for the credential. */
  name: pulumi.Input<string>;
  /** Lifecycle status of the credential. */
  status?: pulumi.Input<string>;
  /** Whether this credential represents an autonomous agent or a human operator. */
  principalType?: pulumi.Input<string>;
  /** When the credential expires and becomes unusable. Null means it never expires. Enforcement is fail-closed in the proxy the instant this time passes, before any cleanup sweep runs. */
  expiresAt?: pulumi.Input<string>;
}

function agentCredentialToState(r: AgentCredentialData) {
  return {
    projectId: r.project_id,
    policyProfileId: r.policy_profile_id,
    name: r.name,
    pgUsername: r.pg_username ?? undefined,
    status: r.status ?? undefined,
    principalType: r.principal_type ?? undefined,
    authMethod: r.auth_method ?? undefined,
    lastUsedAt: r.last_used_at ?? undefined,
    expiresAt: r.expires_at ?? undefined,
    createdAt: r.created_at ?? undefined,
    updatedAt: r.updated_at ?? undefined,
  };
}

const agentCredentialProvider: pulumi.dynamic.ResourceProvider = {
  async create(inputs: Record<string, unknown>) {
    const api = createClient();

    try {
      const result = await api.agents.createAgentCredential({
        pathParams: { project_id: String(inputs.projectId) },
        body: {
          policy_profile_id: String(inputs.policyProfileId),
          name: String(inputs.name),
          principal_type: inputs.principalType as "agent" | "human" | undefined,
          expires_at: inputs.expiresAt as string | undefined,
        },
      });

      const resource = (result as { credential: AgentCredentialData }).credential;
      const connectionStringValue = (result as Record<string, unknown>).connection_string as
        | string
        | undefined;
      const mcpUrlValue = (result as Record<string, unknown>).mcp_url as string | undefined;
      const mcpTokenValue = (result as Record<string, unknown>).mcp_token as string | undefined;
      return {
        id: resource.id,
        outs: stripUndefined({
          ...agentCredentialToState(resource),
          connectionString: connectionStringValue,
          mcpUrl: mcpUrlValue,
          mcpToken: mcpTokenValue,
        }),
      };
    } catch (err) {
      // Adopt orphaned agentCredential on 409 Conflict (e.g. previous create succeeded
      // in the API but Pulumi state was lost due to serialization error).
      if (apiErrorStatus(err) === 409) {
        const name = String(inputs.name);
        const list = (await api.agents.listAgentCredentials({
          pathParams: { project_id: String(inputs.projectId) },
          queryParams: { page_size: 100 },
        })) as { agents: AgentCredentialData[] };
        const existing = list.agents.find((p) => p.name === name);
        if (existing) {
          console.info(`Adopting existing agentCredential "${name}" (${existing.id})`);
          return {
            id: existing.id,
            outs: stripUndefined({
              ...agentCredentialToState(existing),
            }),
          };
        }
      }
      handleApiError("create", "AgentCredential", err);
    }
  },

  async read(id: string, props: Record<string, unknown>) {
    const api = createClient();

    try {
      const resource = (await api.agents.getAgentCredential({
        pathParams: { project_id: String(props.projectId), agent_id: id },
      })) as AgentCredentialData;

      return {
        id,
        props: stripUndefined({
          ...props,
          ...agentCredentialToState(resource),
        }),
      };
    } catch (err) {
      if (apiErrorStatus(err) === 404 && props.name) {
        const list = (await api.agents.listAgentCredentials({
          pathParams: { project_id: String(props.projectId) },
          queryParams: { page_size: 100 },
        })) as { agents: AgentCredentialData[] };
        const matchName = String(props.name);
        const existing = list.agents.find((p) => p.name === matchName);
        if (existing) {
          console.info(
            `Re-adopting agentCredential "${matchName}" (${existing.id}) during read after out-of-band deletion`,
          );
          return {
            id: existing.id,
            props: stripUndefined({
              ...props,
              ...agentCredentialToState(existing),
            }),
          };
        }
        console.warn(
          `AgentCredential "${matchName}" (${id}) not found during read — it may have been deleted out-of-band.`,
        );
        return { id, props };
      }
      handleApiError("read", "AgentCredential", err);
    }
  },

  async update(id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const api = createClient();

    try {
      const body: Record<string, unknown> = {};
      if (news.status !== olds.status) body.status = news.status;

      if (Object.keys(body).length > 0) {
        await api.agents.updateAgentCredentialStatus({
          pathParams: { project_id: String(news.projectId), agent_id: id },
          body: body as Parameters<typeof api.agents.updateAgentCredentialStatus>[0]["body"],
        });
      }

      const resource = (await api.agents.getAgentCredential({
        pathParams: { project_id: String(news.projectId), agent_id: id },
      })) as AgentCredentialData;

      return {
        outs: stripUndefined({
          ...agentCredentialToState(resource),
        }),
      };
    } catch (err) {
      if (apiErrorStatus(err) === 404) {
        throw new Error(
          `AgentCredential "${String(news.name)}" (${id}) was deleted out-of-band. ` +
            `Run \`pulumi refresh\` to reconcile state, then re-run \`pulumi up\`.`,
        );
      }
      handleApiError("update", "AgentCredential", err);
    }
  },

  async delete(id: string, props: Record<string, unknown>) {
    const api = createClient();
    try {
      await api.agents.revokeAgentCredential({
        pathParams: { project_id: String(props.projectId), agent_id: id },
      });
    } catch (err) {
      // 404 means the resource is already gone — treat as success.
      if (apiErrorStatus(err) === 404) return;
      handleApiError("delete", "AgentCredential", err);
    }
  },

  async diff(_id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const replaces: string[] = [];
    if (news.projectId !== olds.projectId) replaces.push("projectId");
    if (news.policyProfileId !== olds.policyProfileId) replaces.push("policyProfileId");
    if (news.name !== olds.name) replaces.push("name");
    if ((news.principalType ?? "agent") !== (olds.principalType ?? "agent"))
      replaces.push("principalType");
    if ((news.expiresAt ?? "") !== (olds.expiresAt ?? "")) replaces.push("expiresAt");

    const changes =
      news.status !== olds.status ||
      news.projectId !== olds.projectId ||
      news.policyProfileId !== olds.policyProfileId ||
      news.name !== olds.name ||
      news.principalType !== olds.principalType ||
      news.expiresAt !== olds.expiresAt ||
      replaces.length > 0;

    return { changes, replaces, deleteBeforeReplace: false };
  },
};

/**
 * Manages a scoped agent credential (a PgBeam-issued Postgres login plus a hosted MCP token) for an AI agent. The connection string and MCP token are one-time secrets returned only at creation and exposed as sensitive computed outputs; they cannot be retrieved again. To rotate the secrets, taint/replace the resource (or use the rotate endpoint out of band).
 */
export class AgentCredential extends pulumi.dynamic.Resource {
  /** Owning project ID. */
  public readonly projectId!: pulumi.Output<string>;
  /** Policy profile enforced for this credential. */
  public readonly policyProfileId!: pulumi.Output<string>;
  /** Human-readable label for the credential. */
  public readonly name!: pulumi.Output<string>;
  /** The Postgres username this credential presents to the proxy. */
  public readonly pgUsername!: pulumi.Output<string | undefined>;
  /** Lifecycle status of the credential. */
  public readonly status!: pulumi.Output<string | undefined>;
  /** Whether this credential represents an autonomous agent or a human operator. */
  public readonly principalType!: pulumi.Output<string | undefined>;
  /** Postgres auth method the proxy presents for this credential. */
  public readonly authMethod!: pulumi.Output<string | undefined>;
  /** When the credential was last used to connect, if ever. */
  public readonly lastUsedAt!: pulumi.Output<string | undefined>;
  /** When the credential expires and becomes unusable. Null means it never expires. Enforcement is fail-closed in the proxy the instant this time passes, before any cleanup sweep runs. */
  public readonly expiresAt!: pulumi.Output<string | undefined>;
  /** When the credential was created. */
  public readonly createdAt!: pulumi.Output<string | undefined>;
  /** When the credential was last updated. */
  public readonly updatedAt!: pulumi.Output<string | undefined>;
  /** One-time guarded Postgres connection string for this agent credential (shown once). */
  public readonly connectionString!: pulumi.Output<string>;
  /** Hosted agent-database MCP endpoint for this project. Use with the mcp_token as a bearer token. */
  public readonly mcpUrl!: pulumi.Output<string>;
  /** One-time bearer token for the hosted MCP endpoint (shown once). */
  public readonly mcpToken!: pulumi.Output<string>;

  constructor(name: string, args: AgentCredentialArgs, opts?: pulumi.CustomResourceOptions) {
    opts = {
      ...opts,
      additionalSecretOutputs: [
        ...(opts?.additionalSecretOutputs ?? []),
        "connectionString",
        "mcpToken",
      ],
    };
    super(
      agentCredentialProvider,
      name,
      {
        ...args,
        pgUsername: undefined,
        authMethod: undefined,
        lastUsedAt: undefined,
        createdAt: undefined,
        updatedAt: undefined,
        connectionString: undefined,
        mcpUrl: undefined,
        mcpToken: undefined,
      },
      opts,
    );
  }
}
