// Code generated by generate-pulumi.ts — DO NOT EDIT.

import * as pulumi from "@pulumi/pulumi";
import type { AnomalyRule as AnomalyRuleData } from "pgbeam";
import {
  apiErrorStatus,
  createClient,
  handleApiError,
  isApiUnreachable,
  warnRefreshSkipped,
} from "./provider.js";
import { stripUndefined } from "./utils.js";

export interface AnomalyRuleArgs {
  /** Project the rule belongs to. */
  projectId: pulumi.Input<string>;
  /** Agent credential the rule applies to. Null applies it to every credential in the project.
   */
  credentialId?: pulumi.Input<string>;
  /** One of the five detection metrics. A rule retunes how sensitive one of them is; it adds no detection algorithm and no alert kind.
   */
  metric: pulumi.Input<string>;
  /** N in the "mean + N * dispersion" spike rule. Null leaves the deployment default in place.
   */
  sigmaThreshold?: pulumi.Input<number | null>;
  /** Absolute floor below which the metric never alerts. Null leaves the deployment default in place. Only queries_per_hour, bytes_per_hour and errors_per_hour have a floor.
   */
  floor?: pulumi.Input<number | null>;
  /** False silences this metric for this scope. Note the polarity is the opposite of honeytokens.enabled: the rule IS the switch, so disabling it disables the metric rather than deactivating the rule.
   */
  enabled?: pulumi.Input<boolean>;
}

function anomalyRuleToState(r: AnomalyRuleData) {
  return {
    projectId: r.project_id,
    credentialId: r.credential_id ?? undefined,
    metric: r.metric,
    sigmaThreshold: r.sigma_threshold ?? null,
    floor: r.floor ?? null,
    enabled: r.enabled ?? undefined,
    createdAt: r.created_at ?? undefined,
    updatedAt: r.updated_at ?? undefined,
  };
}

export const anomalyRuleProvider: pulumi.dynamic.ResourceProvider = {
  async create(inputs: Record<string, unknown>) {
    const api = createClient();

    try {
      const result = await api.anomalies.createAnomalyRule({
        pathParams: { project_id: String(inputs.projectId) },
        body: {
          credential_id: inputs.credentialId as string | undefined,
          metric: inputs.metric as
            | "queries_per_hour"
            | "bytes_per_hour"
            | "distinct_shapes"
            | "errors_per_hour"
            | "active_hours",
          sigma_threshold: inputs.sigmaThreshold as number | undefined,
          floor: inputs.floor as number | undefined,
          enabled: inputs.enabled as boolean | undefined,
        },
      });

      const resource = result as AnomalyRuleData;
      return {
        id: resource.id,
        outs: stripUndefined({
          ...anomalyRuleToState(resource),
        }),
      };
    } catch (err) {
      handleApiError("create", "AnomalyRule", err);
    }
  },

  async read(id: string, props: Record<string, unknown>) {
    const api = createClient();

    try {
      const resource = (await api.anomalies.getAnomalyRule({
        pathParams: { project_id: String(props.projectId), anomaly_rule_id: id },
      })) as AnomalyRuleData;

      return {
        id,
        props: stripUndefined({
          ...props,
          ...anomalyRuleToState(resource),
        }),
      };
    } catch (err) {
      if (isApiUnreachable(err)) {
        warnRefreshSkipped("AnomalyRule", id, err);
        return { id, props };
      }

      handleApiError("read", "AnomalyRule", err);
    }
  },

  async update(id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const api = createClient();

    try {
      const changed =
        news.credentialId !== olds.credentialId ||
        news.metric !== olds.metric ||
        news.sigmaThreshold !== olds.sigmaThreshold ||
        news.floor !== olds.floor ||
        news.enabled !== olds.enabled;

      const body: Record<string, unknown> = {};
      body.credential_id = news.credentialId;
      body.metric = news.metric;
      body.sigma_threshold = news.sigmaThreshold;
      body.floor = news.floor;
      body.enabled = news.enabled;

      if (changed) {
        await api.anomalies.updateAnomalyRule({
          pathParams: { project_id: String(news.projectId), anomaly_rule_id: id },
          body: body as Parameters<typeof api.anomalies.updateAnomalyRule>[0]["body"],
        });
      }

      const resource = (await api.anomalies.getAnomalyRule({
        pathParams: { project_id: String(news.projectId), anomaly_rule_id: id },
      })) as AnomalyRuleData;

      return {
        outs: stripUndefined({
          ...anomalyRuleToState(resource),
        }),
      };
    } catch (err) {
      const status = apiErrorStatus(err);
      if (status === undefined || status >= 500) {
        const detail = status ? `(${status})` : `(network error)`;
        console.warn(
          `PgBeam API unavailable ${detail} during anomalyRule update — preserving previous state.`,
        );
        return { outs: stripUndefined({ ...(olds as Record<string, unknown>) }) };
      }
      handleApiError("update", "AnomalyRule", err);
    }
  },

  async delete(id: string, props: Record<string, unknown>) {
    const api = createClient();
    try {
      await api.anomalies.deleteAnomalyRule({
        pathParams: { project_id: String(props.projectId), anomaly_rule_id: id },
      });
    } catch (err) {
      // 404 means the resource is already gone — treat as success.
      if (apiErrorStatus(err) === 404) return;
      handleApiError("delete", "AnomalyRule", err);
    }
  },

  async diff(_id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const replaces: string[] = [];
    if (news.projectId !== olds.projectId) replaces.push("projectId");

    const changes =
      news.credentialId !== olds.credentialId ||
      news.metric !== olds.metric ||
      (news.sigmaThreshold ?? 0) !== (olds.sigmaThreshold ?? 0) ||
      (news.floor ?? 0) !== (olds.floor ?? 0) ||
      news.enabled !== olds.enabled ||
      news.projectId !== olds.projectId ||
      replaces.length > 0;

    return { changes, replaces, deleteBeforeReplace: false };
  },
};

/**
 * Manages an anomaly rule: the sensitivity of one detection metric for one project, or for one agent credential in it. Without a rule every metric resolves to the deployment default, so a credential that legitimately runs at 3am cannot be exempted and a noisy one cannot be loosened. Note the polarity of enabled: the rule IS the switch, so enabled=false silences the metric for that scope rather than deactivating the rule. One rule exists per (project, credential, metric); a second one for the same scope is a conflict. Detection runs in the control plane and re-reads the rules on every pass, so a write takes effect at the next detection pass rather than being pushed to the proxy.
 */
export class AnomalyRule extends pulumi.dynamic.Resource {
  /** Project the rule belongs to. */
  public readonly projectId!: pulumi.Output<string>;
  /** Agent credential the rule applies to. Null applies it to every credential in the project.
   */
  public readonly credentialId!: pulumi.Output<string | undefined>;
  /** One of the five detection metrics. A rule retunes how sensitive one of them is; it adds no detection algorithm and no alert kind.
   */
  public readonly metric!: pulumi.Output<string>;
  /** N in the "mean + N * dispersion" spike rule. Null leaves the deployment default in place.
   */
  public readonly sigmaThreshold!: pulumi.Output<number | null>;
  /** Absolute floor below which the metric never alerts. Null leaves the deployment default in place. Only queries_per_hour, bytes_per_hour and errors_per_hour have a floor.
   */
  public readonly floor!: pulumi.Output<number | null>;
  /** False silences this metric for this scope. Note the polarity is the opposite of honeytokens.enabled: the rule IS the switch, so disabling it disables the metric rather than deactivating the rule.
   */
  public readonly enabled!: pulumi.Output<boolean | undefined>;
  /** When the rule was created. */
  public readonly createdAt!: pulumi.Output<string | undefined>;
  /** When the rule was last updated. */
  public readonly updatedAt!: pulumi.Output<string | undefined>;

  constructor(name: string, args: AnomalyRuleArgs, opts?: pulumi.CustomResourceOptions) {
    super(
      anomalyRuleProvider,
      name,
      {
        ...args,
        createdAt: undefined,
        updatedAt: undefined,
      },
      opts,
    );
  }
}
