// Code generated by generate-pulumi.ts — DO NOT EDIT.

import * as pulumi from "@pulumi/pulumi";
import type { CacheRuleEntry } from "pgbeam";
import { apiErrorStatus, createClient, handleApiError } from "./provider.js";
import { stripUndefined } from "./utils.js";

export interface CacheRuleArgs {
  /** ProjectId parameter. */
  projectId: pulumi.Input<string>;
  /** DatabaseId parameter. */
  databaseId: pulumi.Input<string>;
  /** xxhash64 hex of the normalized SQL. */
  queryHash: pulumi.Input<string>;
  /** Whether caching is enabled for this query shape. */
  cacheEnabled: pulumi.Input<boolean>;
  /** TTL override in seconds. Null means use project default. */
  cacheTtlSeconds?: pulumi.Input<number | null>;
  /** SWR override in seconds. Null means use project default. */
  cacheSwrSeconds?: pulumi.Input<number | null>;
}

function cacheRuleToState(r: CacheRuleEntry) {
  return {
    queryHash: r.query_hash ?? undefined,
    normalizedSql: r.normalized_sql ?? undefined,
    queryType: r.query_type ?? undefined,
    cacheEnabled: r.cache_enabled,
    cacheTtlSeconds: r.cache_ttl_seconds ?? null,
    cacheSwrSeconds: r.cache_swr_seconds ?? null,
    callCount: r.call_count ?? null,
    avgLatencyMs: r.avg_latency_ms ?? null,
    p95LatencyMs: r.p95_latency_ms ?? null,
    avgResponseBytes: r.avg_response_bytes ?? null,
    stabilityRate: r.stability_rate ?? null,
    recommendation: r.recommendation ?? undefined,
    firstSeenAt: r.first_seen_at ?? undefined,
    lastSeenAt: r.last_seen_at ?? undefined,
  };
}

const cacheRuleProvider: pulumi.dynamic.ResourceProvider = {
  async create(inputs: Record<string, unknown>) {
    const api = createClient();

    try {
      const result = await api.projects.updateCacheRule({
        pathParams: {
          project_id: String(inputs.projectId),
          database_id: String(inputs.databaseId),
          query_hash: String(inputs.queryHash),
        },
        body: {
          cache_enabled: Boolean(inputs.cacheEnabled),
          cache_ttl_seconds: inputs.cacheTtlSeconds as number | null | undefined,
          cache_swr_seconds: inputs.cacheSwrSeconds as number | null | undefined,
        },
      });

      const response = result as { entry: CacheRuleEntry };
      const id = `${inputs.projectId}/${inputs.databaseId}/${inputs.queryHash}`;

      return {
        id,
        outs: stripUndefined({
          ...cacheRuleToState(response.entry),
        }),
      };
    } catch (err) {
      handleApiError("create", "CacheRule", err);
    }
  },

  async read(id: string, props: Record<string, unknown>) {
    const api = createClient();

    try {
      let found: CacheRuleEntry | undefined;
      let pageToken: string | undefined;

      do {
        const result = await api.projects.listCacheRules({
          pathParams: {
            project_id: String(props.projectId),
            database_id: String(props.databaseId),
          },
          queryParams: {
            page_size: 100,
            ...(pageToken ? { page_token: pageToken } : {}),
          },
        });

        const response = result as {
          entries: CacheRuleEntry[];
          next_page_token?: string;
        };
        found = response.entries?.find((e) => e.query_hash === props.queryHash);
        pageToken = response.next_page_token;
      } while (!found && pageToken);

      if (!found) {
        throw new Error(`CacheRule ${id} not found`);
      }

      return {
        id,
        props: stripUndefined({
          ...props,
          ...cacheRuleToState(found),
        }),
      };
    } catch (err) {
      handleApiError("read", "CacheRule", err);
    }
  },

  async update(_id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const api = createClient();

    try {
      const result = await api.projects.updateCacheRule({
        pathParams: {
          project_id: String(news.projectId),
          database_id: String(news.databaseId),
          query_hash: String(news.queryHash),
        },
        body: {
          cache_enabled: Boolean(news.cacheEnabled),
          cache_ttl_seconds: news.cacheTtlSeconds as number | null | undefined,
          cache_swr_seconds: news.cacheSwrSeconds as number | null | undefined,
        },
      });

      const response = result as { entry: CacheRuleEntry };
      return {
        outs: stripUndefined({
          ...cacheRuleToState(response.entry),
        }),
      };
    } catch (err) {
      const status = apiErrorStatus(err);
      if (status === undefined || status >= 500) {
        const detail = status ? `(${status})` : `(network error)`;
        pulumi.log.warn(
          `PgBeam API unavailable ${detail} during cacheRule update — preserving previous state.`,
        );
        return { outs: stripUndefined({ ...(olds as Record<string, unknown>) }) };
      }
      handleApiError("update", "CacheRule", err);
    }
  },

  async delete(_id: string, props: Record<string, unknown>) {
    const api = createClient();
    try {
      await api.projects.updateCacheRule({
        pathParams: {
          project_id: String(props.projectId),
          database_id: String(props.databaseId),
          query_hash: String(props.queryHash),
        },
        body: {
          cache_enabled: false,
          cache_ttl_seconds: null,
          cache_swr_seconds: null,
        },
      });
    } catch (err) {
      // 404 means the resource is already gone — treat as success.
      if (apiErrorStatus(err) === 404) return;
      handleApiError("delete", "CacheRule", err);
    }
  },

  async diff(_id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const replaces: string[] = [];
    if (news.projectId !== olds.projectId) replaces.push("projectId");
    if (news.databaseId !== olds.databaseId) replaces.push("databaseId");
    if (news.queryHash !== olds.queryHash) replaces.push("queryHash");

    const changes =
      news.cacheEnabled !== olds.cacheEnabled ||
      (news.cacheTtlSeconds ?? 0) !== (olds.cacheTtlSeconds ?? 0) ||
      (news.cacheSwrSeconds ?? 0) !== (olds.cacheSwrSeconds ?? 0) ||
      replaces.length > 0;

    return { changes, replaces, deleteBeforeReplace: false };
  },
};

/**
 * Manages a per-query cache rule. Deletion disables caching (soft-delete).
 */
export class CacheRule extends pulumi.dynamic.Resource {
  /** xxhash64 hex of the normalized SQL. */
  public readonly queryHash!: pulumi.Output<string | undefined>;
  /** SQL with literals replaced by $N placeholders. */
  public readonly normalizedSql!: pulumi.Output<string | undefined>;
  /** Query classification. */
  public readonly queryType!: pulumi.Output<string | undefined>;
  /** Whether caching is enabled for this query shape. */
  public readonly cacheEnabled!: pulumi.Output<boolean>;
  /** TTL override in seconds. Null means use project default. */
  public readonly cacheTtlSeconds!: pulumi.Output<number | null>;
  /** SWR override in seconds. Null means use project default. */
  public readonly cacheSwrSeconds!: pulumi.Output<number | null>;
  /** Total number of executions observed. */
  public readonly callCount!: pulumi.Output<number | null>;
  /** Average query latency in milliseconds. */
  public readonly avgLatencyMs!: pulumi.Output<number | null>;
  /** 95th percentile latency in milliseconds. */
  public readonly p95LatencyMs!: pulumi.Output<number | null>;
  /** Average response size in bytes. */
  public readonly avgResponseBytes!: pulumi.Output<number | null>;
  /** Response stability rate (0.0 to 1.0). Higher means more stable. */
  public readonly stabilityRate!: pulumi.Output<number | null>;
  /** Cache recommendation based on frequency, latency, and stability. */
  public readonly recommendation!: pulumi.Output<string | undefined>;
  /** When this query was first observed. */
  public readonly firstSeenAt!: pulumi.Output<string | undefined>;
  /** When this query was last observed. */
  public readonly lastSeenAt!: pulumi.Output<string | undefined>;

  constructor(name: string, args: CacheRuleArgs, opts?: pulumi.CustomResourceOptions) {
    super(
      cacheRuleProvider,
      name,
      {
        ...args,
        queryHash: undefined,
        normalizedSql: undefined,
        queryType: undefined,
        callCount: undefined,
        avgLatencyMs: undefined,
        p95LatencyMs: undefined,
        avgResponseBytes: undefined,
        stabilityRate: undefined,
        recommendation: undefined,
        firstSeenAt: undefined,
        lastSeenAt: undefined,
      },
      opts,
    );
  }
}
