// Code generated by generate-pulumi.ts — DO NOT EDIT.

import * as pulumi from "@pulumi/pulumi";
import type { CustomDomain as CustomDomainData } from "pgbeam";
import { apiErrorStatus, createClient, handleApiError } from "./provider.js";
import { stripUndefined } from "./utils.js";

interface DnsInstructions {
  cnameHost?: string;
  cnameTarget?: string;
  txtHost?: string;
  txtValue?: string;
  acmeCnameHost?: string;
  acmeCnameTarget?: string;
}

export interface CustomDomainArgs {
  /** Owning project ID. */
  projectId: pulumi.Input<string>;
  /** The custom domain name. */
  domain: pulumi.Input<string>;
}

function customDomainToState(r: CustomDomainData) {
  return {
    projectId: r.project_id,
    domain: r.domain,
    verified: r.verified ?? undefined,
    verifiedAt: r.verified_at ?? undefined,
    tlsCertExpiry: r.tls_cert_expiry ?? undefined,
    dnsVerificationToken: r.dns_verification_token ?? undefined,
    dnsInstructions: r.dns_instructions
      ? {
          cnameHost: r.dns_instructions.cname_host ?? undefined,
          cnameTarget: r.dns_instructions.cname_target ?? undefined,
          txtHost: r.dns_instructions.txt_host ?? undefined,
          txtValue: r.dns_instructions.txt_value ?? undefined,
          acmeCnameHost: r.dns_instructions.acme_cname_host ?? undefined,
          acmeCnameTarget: r.dns_instructions.acme_cname_target ?? undefined,
        }
      : undefined,
    createdAt: r.created_at ?? undefined,
    updatedAt: r.updated_at ?? undefined,
  };
}

const customDomainProvider: pulumi.dynamic.ResourceProvider = {
  async create(inputs: Record<string, unknown>) {
    const api = createClient();

    try {
      const result = await api.projects.createCustomDomain({
        pathParams: { project_id: String(inputs.projectId) },
        body: {
          domain: String(inputs.domain),
        },
      });

      const resource = result as CustomDomainData;
      return {
        id: resource.id,
        outs: stripUndefined({
          ...customDomainToState(resource),
        }),
      };
    } catch (err) {
      handleApiError("create", "CustomDomain", err);
    }
  },

  async read(id: string, props: Record<string, unknown>) {
    const api = createClient();

    try {
      let found: CustomDomainData | undefined;
      let pageToken: string | undefined;

      do {
        const result = await api.projects.listCustomDomains({
          pathParams: { project_id: String(props.projectId) },
          queryParams: {
            page_size: 100,
            ...(pageToken ? { page_token: pageToken } : {}),
          },
        });

        const response = result as {
          domains: CustomDomainData[];
          next_page_token?: string;
        };
        found = response.domains.find((e) => e.id === id);
        pageToken = response.next_page_token;
      } while (!found && pageToken);

      if (!found) {
        throw new Error(`CustomDomain ${id} not found`);
      }

      return {
        id,
        props: stripUndefined({
          ...props,
          ...customDomainToState(found),
        }),
      };
    } catch (err) {
      handleApiError("read", "CustomDomain", err);
    }
  },

  async delete(id: string, props: Record<string, unknown>) {
    const api = createClient();
    try {
      await api.projects.deleteCustomDomain({
        pathParams: { project_id: String(props.projectId), domain_id: id },
      });
    } catch (err) {
      // 404 means the resource is already gone — treat as success.
      if (apiErrorStatus(err) === 404) return;
      handleApiError("delete", "CustomDomain", err);
    }
  },

  async diff(_id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const replaces: string[] = [];
    if (news.projectId !== olds.projectId) replaces.push("projectId");
    if (news.domain !== olds.domain) replaces.push("domain");

    return {
      changes: replaces.length > 0,
      replaces,
      deleteBeforeReplace: true,
    };
  },
};

/**
 * Manages a custom domain for a PgBeam project.
 */
export class CustomDomain extends pulumi.dynamic.Resource {
  /** Owning project ID. */
  public readonly projectId!: pulumi.Output<string>;
  /** The custom domain name. */
  public readonly domain!: pulumi.Output<string>;
  /** Whether DNS ownership has been verified. */
  public readonly verified!: pulumi.Output<boolean | undefined>;
  /** When DNS verification was completed. */
  public readonly verifiedAt!: pulumi.Output<string | undefined>;
  /** When the TLS certificate expires. */
  public readonly tlsCertExpiry!: pulumi.Output<string | undefined>;
  /** Token value for the DNS TXT record verification. */
  public readonly dnsVerificationToken!: pulumi.Output<string | undefined>;
  /** DNS records the user needs to create for domain verification. */
  public readonly dnsInstructions!: pulumi.Output<DnsInstructions | undefined>;
  /** When the custom domain was created. */
  public readonly createdAt!: pulumi.Output<string | undefined>;
  /** When the custom domain was last updated. */
  public readonly updatedAt!: pulumi.Output<string | undefined>;

  constructor(name: string, args: CustomDomainArgs, opts?: pulumi.CustomResourceOptions) {
    super(
      customDomainProvider,
      name,
      {
        ...args,
        verified: undefined,
        verifiedAt: undefined,
        tlsCertExpiry: undefined,
        dnsVerificationToken: undefined,
        dnsInstructions: undefined,
        createdAt: undefined,
        updatedAt: undefined,
      },
      opts,
    );
  }
}

/**
 * Verify a custom domain.
 *
 * This is a runtime operation (not a Pulumi resource) — call it from an
 * `apply()` or after stack deployment.
 */
export async function verifyCustomDomain(
  projectId: string,
  domainId: string,
): Promise<{ verified: boolean; error?: string }> {
  const api = createClient();
  const result = await api.projects.verifyCustomDomain({
    pathParams: {
      project_id: projectId,
      domain_id: domainId,
    },
  });
  const response = result as { verified: boolean; error?: string };
  return { verified: response.verified, error: response.error };
}
