// Code generated by generate-pulumi.ts — DO NOT EDIT.

import * as pulumi from "@pulumi/pulumi";
import type { Database as DatabaseData } from "pgbeam";
import { apiErrorStatus, createClient, handleApiError } from "./provider.js";
import { stripUndefined } from "./utils.js";

interface CacheConfig {
  enabled: boolean;
  ttlSeconds: number;
  maxEntries: number;
  swrSeconds: number;
}

export interface CacheConfigArgs {
  enabled: boolean;
  ttlSeconds: number;
  maxEntries: number;
  swrSeconds: number;
}

function toApiCacheConfig(c: Record<string, unknown> | undefined) {
  if (!c) return undefined;
  return {
    enabled: Boolean(c.enabled),
    ttl_seconds: Number(c.ttlSeconds),
    max_entries: Number(c.maxEntries),
    swr_seconds: Number(c.swrSeconds),
  };
}

interface PoolConfig {
  poolSize: number;
  minPoolSize: number;
  poolMode: string;
  maxActive?: number;
}

export interface PoolConfigArgs {
  poolSize: number;
  minPoolSize: number;
  poolMode: string;
  maxActive?: number;
}

function toApiPoolConfig(c: Record<string, unknown> | undefined) {
  if (!c) return undefined;
  return {
    pool_size: Number(c.poolSize),
    min_pool_size: Number(c.minPoolSize),
    pool_mode: c.poolMode as "session" | "transaction" | "statement",
    max_active: Number(c.maxActive),
  };
}

export interface DatabaseArgs {
  /** Owning project ID. */
  projectId: pulumi.Input<string>;
  /** PostgreSQL host. */
  host: pulumi.Input<string>;
  /** PostgreSQL port. */
  port: pulumi.Input<number>;
  /** PostgreSQL database name. */
  name: pulumi.Input<string>;
  /** PostgreSQL username. */
  username: pulumi.Input<string>;
  /** PostgreSQL SSL connection mode. */
  sslMode?: pulumi.Input<string>;
  /** Database role. Primary receives writes, replicas receive reads. */
  role?: pulumi.Input<string>;
  /** Region where the connection pool is maintained (near the database). When set and different from the client's edge region, queries are relayed through the pool region's data plane. Empty means direct connection.
   */
  poolRegion?: pulumi.Input<string>;
  /** Query timeout in milliseconds. When set (> 0), the proxy sends SET statement_timeout on upstream connections. 0 means disabled (default).
   */
  queryTimeoutMs?: pulumi.Input<number | null>;
  /** When enabled and replicas are configured, SELECT queries automatically route to read replicas without requiring the @pgbeam:replica SQL annotation.
   */
  autoReadRouting?: pulumi.Input<boolean>;
  /** Query cache configuration. */
  cacheConfig?: pulumi.Input<CacheConfigArgs>;
  /** Connection pool configuration. */
  poolConfig?: pulumi.Input<PoolConfigArgs>;
  /** PostgreSQL password. Stored encrypted at rest. */
  password: pulumi.Input<string>;
}

function databaseToState(r: DatabaseData) {
  return {
    projectId: r.project_id,
    connectionString: r.connection_string ?? undefined,
    host: r.host,
    port: r.port,
    name: r.name,
    username: r.username,
    sslMode: r.ssl_mode ?? undefined,
    role: r.role ?? undefined,
    poolRegion: r.pool_region ?? undefined,
    queryTimeoutMs: r.query_timeout_ms ?? null,
    autoReadRouting: r.auto_read_routing ?? undefined,
    cacheConfig: r.cache_config
      ? {
          enabled: r.cache_config.enabled,
          ttlSeconds: r.cache_config.ttl_seconds,
          maxEntries: r.cache_config.max_entries,
          swrSeconds: r.cache_config.swr_seconds,
        }
      : undefined,
    poolConfig: r.pool_config
      ? {
          poolSize: r.pool_config.pool_size,
          minPoolSize: r.pool_config.min_pool_size,
          poolMode: r.pool_config.pool_mode,
          maxActive: r.pool_config.max_active ?? undefined,
        }
      : undefined,
    createdAt: r.created_at ?? undefined,
    updatedAt: r.updated_at ?? undefined,
  };
}

const databaseProvider: pulumi.dynamic.ResourceProvider = {
  async create(inputs: Record<string, unknown>) {
    const api = createClient();

    try {
      const result = await api.databases.createDatabase({
        pathParams: { project_id: String(inputs.projectId) },
        body: {
          host: String(inputs.host),
          port: Number(inputs.port),
          name: String(inputs.name),
          username: String(inputs.username),
          ssl_mode: inputs.sslMode as
            | "disable"
            | "allow"
            | "prefer"
            | "require"
            | "verify-ca"
            | "verify-full"
            | undefined,
          role: inputs.role as "primary" | "replica" | undefined,
          pool_region: inputs.poolRegion as string | undefined,
          query_timeout_ms: inputs.queryTimeoutMs as number | undefined,
          auto_read_routing: inputs.autoReadRouting as boolean | undefined,
          cache_config: toApiCacheConfig(inputs.cacheConfig as Record<string, unknown> | undefined),
          pool_config: toApiPoolConfig(inputs.poolConfig as Record<string, unknown> | undefined),
          password: String(inputs.password),
        },
      });

      const resource = result as DatabaseData;
      return {
        id: resource.id,
        outs: stripUndefined({
          ...databaseToState(resource),
          password: inputs.password,
        }),
      };
    } catch (err) {
      handleApiError("create", "Database", err);
    }
  },

  async read(id: string, props: Record<string, unknown>) {
    const api = createClient();

    try {
      const resource = (await api.databases.getDatabase({
        pathParams: { project_id: String(props.projectId), database_id: id },
      })) as DatabaseData;

      return {
        id,
        props: stripUndefined({
          ...props,
          ...databaseToState(resource),
        }),
      };
    } catch (err) {
      handleApiError("read", "Database", err);
    }
  },

  async update(id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const api = createClient();

    try {
      const body: Record<string, unknown> = {};
      if (news.host !== olds.host) body.host = news.host;
      if (news.port !== olds.port) body.port = news.port;
      if (news.name !== olds.name) body.name = news.name;
      if (news.username !== olds.username) body.username = news.username;
      if (news.sslMode !== olds.sslMode) body.ssl_mode = news.sslMode;
      if (news.role !== olds.role) body.role = news.role;
      if (news.poolRegion !== olds.poolRegion) body.pool_region = news.poolRegion;
      if (news.queryTimeoutMs !== olds.queryTimeoutMs) body.query_timeout_ms = news.queryTimeoutMs;
      if (news.autoReadRouting !== olds.autoReadRouting)
        body.auto_read_routing = news.autoReadRouting;
      if (JSON.stringify(news.cacheConfig) !== JSON.stringify(olds.cacheConfig))
        body.cache_config = toApiCacheConfig(
          news.cacheConfig as Record<string, unknown> | undefined,
        );
      if (JSON.stringify(news.poolConfig) !== JSON.stringify(olds.poolConfig))
        body.pool_config = toApiPoolConfig(news.poolConfig as Record<string, unknown> | undefined);
      if (news.password !== olds.password) body.password = news.password;

      if (Object.keys(body).length > 0) {
        await api.databases.updateDatabase({
          pathParams: { project_id: String(news.projectId), database_id: id },
          body: body as Parameters<typeof api.databases.updateDatabase>[0]["body"],
        });
      }

      const resource = (await api.databases.getDatabase({
        pathParams: { project_id: String(news.projectId), database_id: id },
      })) as DatabaseData;

      return {
        outs: stripUndefined({
          ...databaseToState(resource),
          password: news.password,
        }),
      };
    } catch (err) {
      const status = apiErrorStatus(err);
      if (status === undefined || status >= 500) {
        const detail = status ? `(${status})` : `(network error)`;
        pulumi.log.warn(
          `PgBeam API unavailable ${detail} during database update — preserving previous state.`,
        );
        return { outs: stripUndefined({ ...(olds as Record<string, unknown>) }) };
      }
      handleApiError("update", "Database", err);
    }
  },

  async delete(id: string, props: Record<string, unknown>) {
    const api = createClient();
    try {
      await api.databases.deleteDatabase({
        pathParams: { project_id: String(props.projectId), database_id: id },
      });
    } catch (err) {
      // 404 means the resource is already gone — treat as success.
      if (apiErrorStatus(err) === 404) return;
      handleApiError("delete", "Database", err);
    }
  },

  async diff(_id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const replaces: string[] = [];
    if (news.projectId !== olds.projectId) replaces.push("projectId");

    const changes =
      news.host !== olds.host ||
      news.port !== olds.port ||
      news.name !== olds.name ||
      news.username !== olds.username ||
      news.sslMode !== olds.sslMode ||
      news.role !== olds.role ||
      news.poolRegion !== olds.poolRegion ||
      (news.queryTimeoutMs ?? 0) !== (olds.queryTimeoutMs ?? 0) ||
      news.autoReadRouting !== olds.autoReadRouting ||
      JSON.stringify(news.cacheConfig) !== JSON.stringify(olds.cacheConfig) ||
      JSON.stringify(news.poolConfig) !== JSON.stringify(olds.poolConfig) ||
      news.password !== olds.password ||
      news.projectId !== olds.projectId ||
      replaces.length > 0;

    return { changes, replaces, deleteBeforeReplace: false };
  },
};

/**
 * Manages an upstream database connection within a PgBeam project.
 */
export class Database extends pulumi.dynamic.Resource {
  /** Owning project ID. */
  public readonly projectId!: pulumi.Output<string>;
  /** Connection string for connecting through PgBeam proxy. Password is replaced with a placeholder. */
  public readonly connectionString!: pulumi.Output<string | undefined>;
  /** PostgreSQL host. */
  public readonly host!: pulumi.Output<string>;
  /** PostgreSQL port. */
  public readonly port!: pulumi.Output<number>;
  /** PostgreSQL database name. */
  public readonly name!: pulumi.Output<string>;
  /** PostgreSQL username. */
  public readonly username!: pulumi.Output<string>;
  /** PostgreSQL SSL connection mode. */
  public readonly sslMode!: pulumi.Output<string | undefined>;
  /** Database role. Primary receives writes, replicas receive reads. */
  public readonly role!: pulumi.Output<string | undefined>;
  /** Region where the connection pool is maintained (near the database). When set and different from the client's edge region, queries are relayed through the pool region's data plane. Empty means direct connection.
   */
  public readonly poolRegion!: pulumi.Output<string | undefined>;
  /** Query timeout in milliseconds. When set (> 0), the proxy sends SET statement_timeout on upstream connections. 0 means disabled (default).
   */
  public readonly queryTimeoutMs!: pulumi.Output<number | null>;
  /** When enabled and replicas are configured, SELECT queries automatically route to read replicas without requiring the @pgbeam:replica SQL annotation.
   */
  public readonly autoReadRouting!: pulumi.Output<boolean | undefined>;
  /** Query cache configuration. */
  public readonly cacheConfig!: pulumi.Output<CacheConfig | undefined>;
  /** Connection pool configuration. */
  public readonly poolConfig!: pulumi.Output<PoolConfig | undefined>;
  /** When the database registration was created. */
  public readonly createdAt!: pulumi.Output<string | undefined>;
  /** When the database registration was last updated. */
  public readonly updatedAt!: pulumi.Output<string | undefined>;
  /** PostgreSQL password. Stored encrypted at rest. */
  public readonly password!: pulumi.Output<string>;

  constructor(name: string, args: DatabaseArgs, opts?: pulumi.CustomResourceOptions) {
    super(
      databaseProvider,
      name,
      {
        ...args,
        connectionString: undefined,
        createdAt: undefined,
        updatedAt: undefined,
      },
      opts,
    );
  }
}
