// Code generated by generate-pulumi.ts — DO NOT EDIT.

import * as pulumi from "@pulumi/pulumi";
import type { Honeytoken as HoneytokenData } from "pgbeam";
import {
  apiErrorStatus,
  createClient,
  handleApiError,
  isApiUnreachable,
  warnRefreshSkipped,
} from "./provider.js";
import { stripUndefined } from "./utils.js";

export interface HoneytokenArgs {
  /** Project the honeytoken belongs to. */
  projectId: pulumi.Input<string>;
  /** Optional schema. Null matches the unqualified/public form, mirroring the relation allowlist normalization.
   */
  schemaName?: pulumi.Input<string>;
  /** Relation (table or view) name of the decoy. */
  relationName: pulumi.Input<string>;
  /** Response when tripped. audit_only blocks the statement, records the event, and fires webhooks. kill additionally disables the tripping credential via the kill-switch.
   */
  action: pulumi.Input<string>;
}

function honeytokenToState(r: HoneytokenData) {
  return {
    projectId: r.project_id,
    schemaName: r.schema_name ?? undefined,
    relationName: r.relation_name,
    action: r.action,
    createdAt: r.created_at ?? undefined,
    updatedAt: r.updated_at ?? undefined,
  };
}

export const honeytokenProvider: pulumi.dynamic.ResourceProvider = {
  async create(inputs: Record<string, unknown>) {
    const api = createClient();

    try {
      const result = await api.honeytokens.createHoneytoken({
        pathParams: { project_id: String(inputs.projectId) },
        body: {
          schema_name: inputs.schemaName as string | undefined,
          relation_name: String(inputs.relationName),
          action: inputs.action as "audit_only" | "kill",
        },
      });

      const resource = result as HoneytokenData;
      return {
        id: resource.id,
        outs: stripUndefined({
          ...honeytokenToState(resource),
        }),
      };
    } catch (err) {
      handleApiError("create", "Honeytoken", err);
    }
  },

  async read(id: string, props: Record<string, unknown>) {
    const api = createClient();

    try {
      const resource = (await api.honeytokens.getHoneytoken({
        pathParams: { project_id: String(props.projectId), honeytoken_id: id },
      })) as HoneytokenData;

      return {
        id,
        props: stripUndefined({
          ...props,
          ...honeytokenToState(resource),
        }),
      };
    } catch (err) {
      if (isApiUnreachable(err)) {
        warnRefreshSkipped("Honeytoken", id, err);
        return { id, props };
      }

      handleApiError("read", "Honeytoken", err);
    }
  },

  async update(id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const api = createClient();

    try {
      const changed =
        news.schemaName !== olds.schemaName ||
        news.relationName !== olds.relationName ||
        news.action !== olds.action;

      const body: Record<string, unknown> = {};
      body.schema_name = news.schemaName;
      body.relation_name = news.relationName;
      body.action = news.action;

      if (changed) {
        await api.honeytokens.updateHoneytoken({
          pathParams: { project_id: String(news.projectId), honeytoken_id: id },
          body: body as Parameters<typeof api.honeytokens.updateHoneytoken>[0]["body"],
        });
      }

      const resource = (await api.honeytokens.getHoneytoken({
        pathParams: { project_id: String(news.projectId), honeytoken_id: id },
      })) as HoneytokenData;

      return {
        outs: stripUndefined({
          ...honeytokenToState(resource),
        }),
      };
    } catch (err) {
      const status = apiErrorStatus(err);
      if (status === undefined || status >= 500) {
        const detail = status ? `(${status})` : `(network error)`;
        console.warn(
          `PgBeam API unavailable ${detail} during honeytoken update — preserving previous state.`,
        );
        return { outs: stripUndefined({ ...(olds as Record<string, unknown>) }) };
      }
      handleApiError("update", "Honeytoken", err);
    }
  },

  async delete(id: string, props: Record<string, unknown>) {
    const api = createClient();
    try {
      await api.honeytokens.deleteHoneytoken({
        pathParams: { project_id: String(props.projectId), honeytoken_id: id },
      });
    } catch (err) {
      // 404 means the resource is already gone — treat as success.
      if (apiErrorStatus(err) === 404) return;
      handleApiError("delete", "Honeytoken", err);
    }
  },

  async diff(_id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const replaces: string[] = [];
    if (news.projectId !== olds.projectId) replaces.push("projectId");

    const changes =
      news.schemaName !== olds.schemaName ||
      news.relationName !== olds.relationName ||
      news.action !== olds.action ||
      news.projectId !== olds.projectId ||
      replaces.length > 0;

    return { changes, replaces, deleteBeforeReplace: false };
  },
};

/**
 * Manages a honeytoken: a decoy (canary) relation that no legitimate query should ever touch. Any agent statement referencing it is blocked and recorded as a canary_tripped audit event; the kill action additionally disables the tripping credential via the kill-switch. The relation does not have to exist in the upstream database: enforcement is by name, in the wire protocol, before the statement reaches Postgres.
 */
export class Honeytoken extends pulumi.dynamic.Resource {
  /** Project the honeytoken belongs to. */
  public readonly projectId!: pulumi.Output<string>;
  /** Optional schema. Null matches the unqualified/public form, mirroring the relation allowlist normalization.
   */
  public readonly schemaName!: pulumi.Output<string | undefined>;
  /** Relation (table or view) name of the decoy. */
  public readonly relationName!: pulumi.Output<string>;
  /** Response when tripped. audit_only blocks the statement, records the event, and fires webhooks. kill additionally disables the tripping credential via the kill-switch.
   */
  public readonly action!: pulumi.Output<string>;
  /** When the honeytoken was registered. */
  public readonly createdAt!: pulumi.Output<string | undefined>;
  /** When the honeytoken was last updated. */
  public readonly updatedAt!: pulumi.Output<string | undefined>;

  constructor(name: string, args: HoneytokenArgs, opts?: pulumi.CustomResourceOptions) {
    super(
      honeytokenProvider,
      name,
      {
        ...args,
        createdAt: undefined,
        updatedAt: undefined,
      },
      opts,
    );
  }
}
