// Code generated by generate-pulumi.ts — DO NOT EDIT.

export type {
  CacheConfig,
  CacheRuleEntry,
  CustomDomain as CustomDomainData,
  Database as DatabaseData,
  DatabaseRoleKey as DatabaseRole,
  DnsInstructions,
  OrganizationPlan,
  PlanLimits,
  PoolConfig,
  PoolModeKey as PoolMode,
  Project as ProjectData,
  ProjectStatusKey as ProjectStatus,
  Replica as ReplicaData,
  SSLModeKey as SSLMode,
} from "pgbeam";
export { CacheRule, type CacheRuleArgs } from "./cacheRule.gen.js";
export { CustomDomain, type CustomDomainArgs, verifyCustomDomain } from "./customDomain.gen.js";
export {
  type CacheConfigArgs,
  Database,
  type DatabaseArgs,
  type PoolConfigArgs,
} from "./database.gen.js";
export { Project, type ProjectArgs, type ProjectDatabaseArgs } from "./project.gen.js";
export { configure } from "./provider.js";
export { Replica, type ReplicaArgs } from "./replica.gen.js";
export { SpendLimit, type SpendLimitArgs } from "./spendLimit.gen.js";
