// Code generated by generate-pulumi.ts — DO NOT EDIT.

import * as pulumi from "@pulumi/pulumi";
import type { MaskingRule, PolicyProfile as PolicyProfileData, RowFilter } from "pgbeam";
import { apiErrorStatus, createClient, handleApiError } from "./provider.js";
import { stripUndefined } from "./utils.js";

interface StatementRules {
  allow?: string[];
  deny?: string[];
}

export interface StatementRulesArgs {
  allow?: string[];
  deny?: string[];
}

function toApiStatementRules(c: Record<string, unknown> | undefined) {
  if (!c) return undefined;
  return {
    allow: c.allow as string[] | undefined,
    deny: c.deny as string[] | undefined,
  };
}

export interface MaskingRuleArgs {
  /** Relation name, optionally schema-qualified (e.g. "public.users" or "users"). */
  table: pulumi.Input<string>;
  /** Column to mask. */
  column: pulumi.Input<string>;
  /** How to mask. redact replaces with a token, null returns NULL, hash returns a SHA-256 hex. */
  kind: pulumi.Input<"redact" | "null" | "hash">;
}

function toApiMaskingRule(c: Record<string, unknown>) {
  return {
    table: String(c.table),
    column: String(c.column),
    kind: c.kind as "redact" | "null" | "hash",
  };
}

export interface RowFilterArgs {
  /** Relation name, optionally schema-qualified (e.g. "public.orders"). */
  table: pulumi.Input<string>;
  /** Raw SQL boolean expression ANDed into WHERE for this relation. */
  predicate: pulumi.Input<string>;
}

function toApiRowFilter(c: Record<string, unknown>) {
  return {
    table: String(c.table),
    predicate: String(c.predicate),
  };
}

export interface PolicyProfileArgs {
  /** Owning project ID. */
  projectId: pulumi.Input<string>;
  /** Human-readable name for the policy profile. */
  name: pulumi.Input<string>;
  /** read_only blocks all data and schema mutations. */
  accessMode?: pulumi.Input<string>;
  /** Per-statement-kind allow/deny lists. Empty allow means all kinds permitted by the access mode. */
  statementRules?: pulumi.Input<StatementRulesArgs>;
  /** If non-empty, only these relations are reachable. Schema-qualified or bare names. */
  tableAllowlist?: pulumi.Input<pulumi.Input<string>[]>;
  /** Relations explicitly blocked (takes precedence over the allowlist). */
  tableDenylist?: pulumi.Input<pulumi.Input<string>[]>;
  /** Column masking rules applied to query results. */
  maskingRules?: pulumi.Input<pulumi.Input<MaskingRuleArgs>[]>;
  /** Max queries per rolling hour window. 0 means unlimited. */
  budgetQueriesPerHour?: pulumi.Input<number | null>;
  /** Max queries per day window. 0 means unlimited. */
  budgetQueriesPerDay?: pulumi.Input<number | null>;
  /** Max rows returned per query. 0 means unlimited. */
  maxRows?: pulumi.Input<number | null>;
  /** Upstream statement timeout for agent sessions. 0 uses the project default. */
  statementTimeoutMs?: pulumi.Input<number | null>;
  /** Per-relation row filters ANDed into agent reads. */
  rowFilters?: pulumi.Input<pulumi.Input<RowFilterArgs>[]>;
  /** How writes are handled. normal commits, rollback auto-rolls back, sandbox routes to an ephemeral branch. */
  writeMode?: pulumi.Input<string>;
  /** Which statement classes require human approval before execution. */
  approvalMode?: pulumi.Input<string>;
  /** Statements touching at most this many rows are auto-approved. 0 means none. */
  approvalAutoMaxRows?: pulumi.Input<number | null>;
  /** How long a held statement waits for a decision before expiring. */
  approvalTimeoutSeconds?: pulumi.Input<number | null>;
  /** Migration safety mode. warn surfaces findings, block refuses unsafe DDL. */
  migrationSafety?: pulumi.Input<string>;
  /** Per-day egress budget in bytes. 0 means unlimited. */
  egressBytesPerDay?: pulumi.Input<number | null>;
}

function policyProfileToState(r: PolicyProfileData) {
  return {
    projectId: r.project_id,
    name: r.name,
    accessMode: r.access_mode ?? undefined,
    statementRules: r.statement_rules
      ? {
          allow: r.statement_rules.allow ?? undefined,
          deny: r.statement_rules.deny ?? undefined,
        }
      : undefined,
    tableAllowlist: r.table_allowlist ?? undefined,
    tableDenylist: r.table_denylist ?? undefined,
    maskingRules: r.masking_rules ?? undefined,
    budgetQueriesPerHour: r.budget_queries_per_hour ?? null,
    budgetQueriesPerDay: r.budget_queries_per_day ?? null,
    maxRows: r.max_rows ?? null,
    statementTimeoutMs: r.statement_timeout_ms ?? null,
    rowFilters: r.row_filters ?? undefined,
    writeMode: r.write_mode ?? undefined,
    approvalMode: r.approval_mode ?? undefined,
    approvalAutoMaxRows: r.approval_auto_max_rows ?? null,
    approvalTimeoutSeconds: r.approval_timeout_seconds ?? null,
    migrationSafety: r.migration_safety ?? undefined,
    egressBytesPerDay: r.egress_bytes_per_day ?? null,
    createdAt: r.created_at ?? undefined,
    updatedAt: r.updated_at ?? undefined,
  };
}

const policyProfileProvider: pulumi.dynamic.ResourceProvider = {
  async create(inputs: Record<string, unknown>) {
    const api = createClient();

    try {
      const result = await api.policies.createPolicyProfile({
        pathParams: { project_id: String(inputs.projectId) },
        body: {
          name: String(inputs.name),
          access_mode: inputs.accessMode as "read_only" | "read_write" | undefined,
          statement_rules: toApiStatementRules(
            inputs.statementRules as Record<string, unknown> | undefined,
          ),
          table_allowlist: inputs.tableAllowlist as string[] | undefined,
          table_denylist: inputs.tableDenylist as string[] | undefined,
          masking_rules: (inputs.maskingRules as Record<string, unknown>[] | undefined)?.map(
            toApiMaskingRule,
          ),
          budget_queries_per_hour: inputs.budgetQueriesPerHour as number | undefined,
          budget_queries_per_day: inputs.budgetQueriesPerDay as number | undefined,
          max_rows: inputs.maxRows as number | undefined,
          statement_timeout_ms: inputs.statementTimeoutMs as number | undefined,
          row_filters: (inputs.rowFilters as Record<string, unknown>[] | undefined)?.map(
            toApiRowFilter,
          ),
          write_mode: inputs.writeMode as "normal" | "rollback" | "sandbox" | undefined,
          approval_mode: inputs.approvalMode as "off" | "writes" | "ddl" | "all" | undefined,
          approval_auto_max_rows: inputs.approvalAutoMaxRows as number | undefined,
          approval_timeout_seconds: inputs.approvalTimeoutSeconds as number | undefined,
          migration_safety: inputs.migrationSafety as "off" | "warn" | "block" | undefined,
          egress_bytes_per_day: inputs.egressBytesPerDay as number | undefined,
        },
      });

      const resource = result as PolicyProfileData;
      return {
        id: resource.id,
        outs: stripUndefined({
          ...policyProfileToState(resource),
        }),
      };
    } catch (err) {
      // Adopt orphaned policyProfile on 409 Conflict (e.g. previous create succeeded
      // in the API but Pulumi state was lost due to serialization error).
      if (apiErrorStatus(err) === 409) {
        const name = String(inputs.name);
        const list = (await api.policies.listPolicyProfiles({
          pathParams: { project_id: String(inputs.projectId) },
          queryParams: { page_size: 100 },
        })) as { policies: PolicyProfileData[] };
        const existing = list.policies.find((p) => p.name === name);
        if (existing) {
          console.info(`Adopting existing policyProfile "${name}" (${existing.id})`);
          return {
            id: existing.id,
            outs: stripUndefined({
              ...policyProfileToState(existing),
            }),
          };
        }
      }
      handleApiError("create", "PolicyProfile", err);
    }
  },

  async read(id: string, props: Record<string, unknown>) {
    const api = createClient();

    try {
      const resource = (await api.policies.getPolicyProfile({
        pathParams: { project_id: String(props.projectId), policy_id: id },
      })) as PolicyProfileData;

      return {
        id,
        props: stripUndefined({
          ...props,
          ...policyProfileToState(resource),
        }),
      };
    } catch (err) {
      if (apiErrorStatus(err) === 404 && props.name) {
        const list = (await api.policies.listPolicyProfiles({
          pathParams: { project_id: String(props.projectId) },
          queryParams: { page_size: 100 },
        })) as { policies: PolicyProfileData[] };
        const matchName = String(props.name);
        const existing = list.policies.find((p) => p.name === matchName);
        if (existing) {
          console.info(
            `Re-adopting policyProfile "${matchName}" (${existing.id}) during read after out-of-band deletion`,
          );
          return {
            id: existing.id,
            props: stripUndefined({
              ...props,
              ...policyProfileToState(existing),
            }),
          };
        }
        console.warn(
          `PolicyProfile "${matchName}" (${id}) not found during read — it may have been deleted out-of-band.`,
        );
        return { id, props };
      }
      handleApiError("read", "PolicyProfile", err);
    }
  },

  async update(id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const api = createClient();

    try {
      const body: Record<string, unknown> = {};
      if (news.name !== olds.name) body.name = news.name;
      if (news.accessMode !== olds.accessMode) body.access_mode = news.accessMode;
      if (JSON.stringify(news.statementRules) !== JSON.stringify(olds.statementRules))
        body.statement_rules = toApiStatementRules(
          news.statementRules as Record<string, unknown> | undefined,
        );
      if (JSON.stringify(news.tableAllowlist) !== JSON.stringify(olds.tableAllowlist))
        body.table_allowlist = news.tableAllowlist;
      if (JSON.stringify(news.tableDenylist) !== JSON.stringify(olds.tableDenylist))
        body.table_denylist = news.tableDenylist;
      if (JSON.stringify(news.maskingRules) !== JSON.stringify(olds.maskingRules))
        body.masking_rules = (news.maskingRules as Record<string, unknown>[] | undefined)?.map(
          toApiMaskingRule,
        );
      if (news.budgetQueriesPerHour !== olds.budgetQueriesPerHour)
        body.budget_queries_per_hour = news.budgetQueriesPerHour;
      if (news.budgetQueriesPerDay !== olds.budgetQueriesPerDay)
        body.budget_queries_per_day = news.budgetQueriesPerDay;
      if (news.maxRows !== olds.maxRows) body.max_rows = news.maxRows;
      if (news.statementTimeoutMs !== olds.statementTimeoutMs)
        body.statement_timeout_ms = news.statementTimeoutMs;
      if (JSON.stringify(news.rowFilters) !== JSON.stringify(olds.rowFilters))
        body.row_filters = (news.rowFilters as Record<string, unknown>[] | undefined)?.map(
          toApiRowFilter,
        );
      if (news.writeMode !== olds.writeMode) body.write_mode = news.writeMode;
      if (news.approvalMode !== olds.approvalMode) body.approval_mode = news.approvalMode;
      if (news.approvalAutoMaxRows !== olds.approvalAutoMaxRows)
        body.approval_auto_max_rows = news.approvalAutoMaxRows;
      if (news.approvalTimeoutSeconds !== olds.approvalTimeoutSeconds)
        body.approval_timeout_seconds = news.approvalTimeoutSeconds;
      if (news.migrationSafety !== olds.migrationSafety)
        body.migration_safety = news.migrationSafety;
      if (news.egressBytesPerDay !== olds.egressBytesPerDay)
        body.egress_bytes_per_day = news.egressBytesPerDay;

      if (Object.keys(body).length > 0) {
        await api.policies.updatePolicyProfile({
          pathParams: { project_id: String(news.projectId), policy_id: id },
          body: body as Parameters<typeof api.policies.updatePolicyProfile>[0]["body"],
        });
      }

      const resource = (await api.policies.getPolicyProfile({
        pathParams: { project_id: String(news.projectId), policy_id: id },
      })) as PolicyProfileData;

      return {
        outs: stripUndefined({
          ...policyProfileToState(resource),
        }),
      };
    } catch (err) {
      const status = apiErrorStatus(err);
      if (status === undefined || status >= 500) {
        const detail = status ? `(${status})` : `(network error)`;
        console.warn(
          `PgBeam API unavailable ${detail} during policyProfile update — preserving previous state.`,
        );
        return { outs: stripUndefined({ ...(olds as Record<string, unknown>) }) };
      }
      if (apiErrorStatus(err) === 404) {
        throw new Error(
          `PolicyProfile "${String(news.name)}" (${id}) was deleted out-of-band. ` +
            `Run \`pulumi refresh\` to reconcile state, then re-run \`pulumi up\`.`,
        );
      }
      handleApiError("update", "PolicyProfile", err);
    }
  },

  async delete(id: string, props: Record<string, unknown>) {
    const api = createClient();
    try {
      await api.policies.deletePolicyProfile({
        pathParams: { project_id: String(props.projectId), policy_id: id },
      });
    } catch (err) {
      // 404 means the resource is already gone — treat as success.
      if (apiErrorStatus(err) === 404) return;
      handleApiError("delete", "PolicyProfile", err);
    }
  },

  async diff(_id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const replaces: string[] = [];
    if (news.projectId !== olds.projectId) replaces.push("projectId");

    const changes =
      news.name !== olds.name ||
      news.accessMode !== olds.accessMode ||
      JSON.stringify(news.statementRules) !== JSON.stringify(olds.statementRules) ||
      JSON.stringify(news.tableAllowlist) !== JSON.stringify(olds.tableAllowlist) ||
      JSON.stringify(news.tableDenylist) !== JSON.stringify(olds.tableDenylist) ||
      JSON.stringify(news.maskingRules) !== JSON.stringify(olds.maskingRules) ||
      (news.budgetQueriesPerHour ?? 0) !== (olds.budgetQueriesPerHour ?? 0) ||
      (news.budgetQueriesPerDay ?? 0) !== (olds.budgetQueriesPerDay ?? 0) ||
      (news.maxRows ?? 0) !== (olds.maxRows ?? 0) ||
      (news.statementTimeoutMs ?? 0) !== (olds.statementTimeoutMs ?? 0) ||
      JSON.stringify(news.rowFilters) !== JSON.stringify(olds.rowFilters) ||
      news.writeMode !== olds.writeMode ||
      news.approvalMode !== olds.approvalMode ||
      (news.approvalAutoMaxRows ?? 0) !== (olds.approvalAutoMaxRows ?? 0) ||
      (news.approvalTimeoutSeconds ?? 0) !== (olds.approvalTimeoutSeconds ?? 0) ||
      news.migrationSafety !== olds.migrationSafety ||
      (news.egressBytesPerDay ?? 0) !== (olds.egressBytesPerDay ?? 0) ||
      news.projectId !== olds.projectId ||
      replaces.length > 0;

    return { changes, replaces, deleteBeforeReplace: false };
  },
};

/**
 * Manages a policy profile: a named bundle of agent-gateway enforcement rules (access mode, table allow/deny lists, statement-kind rules, PII masking rules, per-relation row filters, query/egress budgets, write mode, approvals, and migration safety) attached to agent credentials and enforced in the PG wire protocol. Nested-list fields (masking_rules, row_filters) and the nested statement_rules object are expressed as structured config.
 */
export class PolicyProfile extends pulumi.dynamic.Resource {
  /** Owning project ID. */
  public readonly projectId!: pulumi.Output<string>;
  /** Human-readable name for the policy profile. */
  public readonly name!: pulumi.Output<string>;
  /** read_only blocks all data and schema mutations. */
  public readonly accessMode!: pulumi.Output<string | undefined>;
  /** Per-statement-kind allow/deny lists. Empty allow means all kinds permitted by the access mode. */
  public readonly statementRules!: pulumi.Output<StatementRules | undefined>;
  /** If non-empty, only these relations are reachable. Schema-qualified or bare names. */
  public readonly tableAllowlist!: pulumi.Output<string[] | undefined>;
  /** Relations explicitly blocked (takes precedence over the allowlist). */
  public readonly tableDenylist!: pulumi.Output<string[] | undefined>;
  /** Column masking rules applied to query results. */
  public readonly maskingRules!: pulumi.Output<MaskingRule[] | undefined>;
  /** Max queries per rolling hour window. 0 means unlimited. */
  public readonly budgetQueriesPerHour!: pulumi.Output<number | null>;
  /** Max queries per day window. 0 means unlimited. */
  public readonly budgetQueriesPerDay!: pulumi.Output<number | null>;
  /** Max rows returned per query. 0 means unlimited. */
  public readonly maxRows!: pulumi.Output<number | null>;
  /** Upstream statement timeout for agent sessions. 0 uses the project default. */
  public readonly statementTimeoutMs!: pulumi.Output<number | null>;
  /** Per-relation row filters ANDed into agent reads. */
  public readonly rowFilters!: pulumi.Output<RowFilter[] | undefined>;
  /** How writes are handled. normal commits, rollback auto-rolls back, sandbox routes to an ephemeral branch. */
  public readonly writeMode!: pulumi.Output<string | undefined>;
  /** Which statement classes require human approval before execution. */
  public readonly approvalMode!: pulumi.Output<string | undefined>;
  /** Statements touching at most this many rows are auto-approved. 0 means none. */
  public readonly approvalAutoMaxRows!: pulumi.Output<number | null>;
  /** How long a held statement waits for a decision before expiring. */
  public readonly approvalTimeoutSeconds!: pulumi.Output<number | null>;
  /** Migration safety mode. warn surfaces findings, block refuses unsafe DDL. */
  public readonly migrationSafety!: pulumi.Output<string | undefined>;
  /** Per-day egress budget in bytes. 0 means unlimited. */
  public readonly egressBytesPerDay!: pulumi.Output<number | null>;
  /** When the policy profile was created. */
  public readonly createdAt!: pulumi.Output<string | undefined>;
  /** When the policy profile was last updated. */
  public readonly updatedAt!: pulumi.Output<string | undefined>;

  constructor(name: string, args: PolicyProfileArgs, opts?: pulumi.CustomResourceOptions) {
    super(
      policyProfileProvider,
      name,
      {
        ...args,
        createdAt: undefined,
        updatedAt: undefined,
      },
      opts,
    );
  }
}
