// Code generated by generate-pulumi.ts — DO NOT EDIT.

import * as pulumi from "@pulumi/pulumi";
import type { Project as ProjectData } from "pgbeam";
import { apiErrorStatus, createClient, handleApiError } from "./provider.js";
import { stripUndefined } from "./utils.js";

interface ProjectDatabase {
  host: string;
  port: number;
  name: string;
  username: string;
  sslMode?: string;
  role?: string;
  poolRegion?: string;
  queryTimeoutMs?: number;
  autoReadRouting?: boolean;
  cacheConfig?: object;
  poolConfig?: object;
  password: string;
}

export interface ProjectArgs {
  /** Better Auth organization ID that owns this project. */
  orgId: pulumi.Input<string>;
  /** Human-readable project name. */
  name: pulumi.Input<string>;
  /** Optional project description. */
  description?: pulumi.Input<string>;
  /** User-defined labels applied to the project. */
  tags?: pulumi.Input<pulumi.Input<string>[]>;
  /** Maximum queries per second for this project. 0 means unlimited. */
  queriesPerSecond?: pulumi.Input<number | null>;
  /** Burst allowance above the steady-state rate. 0 uses queries_per_second as burst. */
  burstSize?: pulumi.Input<number | null>;
  /** Maximum concurrent proxy connections. 0 means unlimited. */
  maxConnections?: pulumi.Input<number | null>;
  /** IP filtering rules as CIDR ranges with optional labels. When non-empty, only connections from matching IPs are accepted. Empty array means all IPs are allowed (default). Both IPv4 (e.g. 10.0.0.0/8) and IPv6 (e.g. 2001:db8::/32) are supported.
   */
  allowedCidrs?: pulumi.Input<pulumi.Input<string>[]>;
  /** Project lifecycle status. */
  status?: pulumi.Input<string>;
  /** Cloud provider where the project runs. */
  cloud?: pulumi.Input<string>;
  /** Request body for registering an upstream database. */
  database: pulumi.Input<ProjectDatabaseArgs>;
}

export interface ProjectDatabaseArgs {
  /** PostgreSQL host. */
  host: pulumi.Input<string>;
  /** PostgreSQL port. */
  port: pulumi.Input<number>;
  /** PostgreSQL database name. */
  name: pulumi.Input<string>;
  /** PostgreSQL username. */
  username: pulumi.Input<string>;
  /** PostgreSQL SSL connection mode. */
  sslMode?: pulumi.Input<string>;
  /** Database role. Primary receives writes, replicas receive reads. */
  role?: pulumi.Input<string>;
  /** Region where the connection pool is maintained (near the database). When set and different from the client's edge region, queries are relayed through the pool region's data plane. Empty means direct connection.
   */
  poolRegion?: pulumi.Input<string>;
  /** Query timeout in milliseconds. When set (> 0), the proxy sends SET statement_timeout on upstream connections. 0 means disabled (default).
   */
  queryTimeoutMs?: pulumi.Input<number>;
  /** When enabled and replicas are configured, SELECT queries automatically route to read replicas without requiring the @pgbeam:replica SQL annotation.
   */
  autoReadRouting?: pulumi.Input<boolean>;
  /** Query cache configuration. */
  cacheConfig?: pulumi.Input<CacheConfigArgs>;
  /** Connection pool configuration. */
  poolConfig?: pulumi.Input<PoolConfigArgs>;
  /** PostgreSQL password. Stored encrypted at rest. */
  password: pulumi.Input<string>;
}

interface CacheConfigArgs {
  enabled: boolean;
  ttlSeconds: number;
  maxEntries: number;
  swrSeconds: number;
}

function toApiCacheConfig(c: Record<string, unknown> | undefined) {
  if (!c) return undefined;
  return {
    enabled: Boolean(c.enabled),
    ttl_seconds: Number(c.ttlSeconds),
    max_entries: Number(c.maxEntries),
    swr_seconds: Number(c.swrSeconds),
  };
}

interface PoolConfigArgs {
  poolSize: number;
  minPoolSize: number;
  poolMode: string;
  maxActive?: number;
}

function toApiPoolConfig(c: Record<string, unknown> | undefined) {
  if (!c) return undefined;
  return {
    pool_size: Number(c.poolSize),
    min_pool_size: Number(c.minPoolSize),
    pool_mode: c.poolMode as "session" | "transaction" | "statement",
    max_active: Number(c.maxActive),
  };
}

function projectToState(r: ProjectData) {
  return {
    orgId: r.org_id,
    name: r.name,
    description: r.description ?? undefined,
    tags: r.tags ?? undefined,
    cloud: r.cloud ?? undefined,
    proxyHost: r.proxy_host ?? undefined,
    queriesPerSecond: r.queries_per_second ?? null,
    burstSize: r.burst_size ?? null,
    maxConnections: r.max_connections ?? null,
    allowedCidrs: r.allowed_cidrs ?? undefined,
    databaseCount: r.database_count ?? null,
    activeConnections: r.active_connections ?? null,
    status: r.status ?? undefined,
    createdAt: r.created_at ?? undefined,
    updatedAt: r.updated_at ?? undefined,
  };
}

const projectProvider: pulumi.dynamic.ResourceProvider = {
  async create(inputs: Record<string, unknown>) {
    const api = createClient();

    try {
      const database = inputs.database as Record<string, unknown>;

      const result = await api.projects.createProject({
        body: {
          org_id: String(inputs.orgId),
          name: String(inputs.name),
          description: inputs.description as string | undefined,
          tags: inputs.tags as string[] | undefined,
          cloud: inputs.cloud as "aws" | "azure" | "gcp" | undefined,
          database: {
            host: String(database.host),
            port: Number(database.port),
            name: String(database.name),
            username: String(database.username),
            ssl_mode: database.sslMode as
              | "disable"
              | "allow"
              | "prefer"
              | "require"
              | "verify-ca"
              | "verify-full"
              | undefined,
            role: database.role as "primary" | "replica" | undefined,
            pool_region: database.poolRegion as string | undefined,
            query_timeout_ms: Number(database.queryTimeoutMs),
            auto_read_routing: Boolean(database.autoReadRouting),
            cache_config: toApiCacheConfig(
              database.cacheConfig as Record<string, unknown> | undefined,
            ),
            pool_config: toApiPoolConfig(
              database.poolConfig as Record<string, unknown> | undefined,
            ),
            password: String(database.password),
          },
        },
      });

      const project = result.project;
      const primaryDatabaseIdValue = result.database?.id;

      return {
        id: project.id,
        outs: stripUndefined({
          ...projectToState(project),
          database: inputs.database,
          primaryDatabaseId: primaryDatabaseIdValue,
        }),
      };
    } catch (err) {
      // Adopt orphaned project on 409 Conflict (e.g. previous create succeeded
      // in the API but Pulumi state was lost due to serialization error).
      if (apiErrorStatus(err) === 409) {
        const orgId = String(inputs.orgId);
        const name = String(inputs.name);
        const list = (await api.projects.listProjects({
          queryParams: { org_id: orgId, page_size: 100 },
        })) as { projects: ProjectData[] };
        const existing = list.projects.find((p) => p.name === name);
        if (existing) {
          pulumi.log.info(`Adopting existing project "${name}" (${existing.id})`);
          return {
            id: existing.id,
            outs: stripUndefined({
              ...projectToState(existing),
              database: inputs.database,
            }),
          };
        }
      }
      handleApiError("create", "Project", err);
    }
  },

  async read(id: string, props: Record<string, unknown>) {
    const api = createClient();

    try {
      const resource = (await api.projects.getProject({
        pathParams: { project_id: id },
      })) as ProjectData;

      return {
        id,
        props: stripUndefined({
          ...props,
          ...projectToState(resource),
        }),
      };
    } catch (err) {
      if (apiErrorStatus(err) === 404 && props.name) {
        const orgId = String(props.orgId);
        const list = (await api.projects.listProjects({
          queryParams: { org_id: orgId, page_size: 100 },
        })) as { projects: ProjectData[] };
        const matchName = String(props.name);
        const existing = list.projects.find((p) => p.name === matchName);
        if (existing) {
          pulumi.log.info(
            `Re-adopting project "${matchName}" (${existing.id}) during read after out-of-band deletion`,
          );
          return {
            id: existing.id,
            props: stripUndefined({
              ...props,
              ...projectToState(existing),
            }),
          };
        }
        pulumi.log.warn(
          `Project "${matchName}" (${id}) not found during read — it may have been deleted out-of-band.`,
        );
        return { id, props };
      }
      handleApiError("read", "Project", err);
    }
  },

  async update(id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const api = createClient();

    try {
      const body: Record<string, unknown> = {};
      if (news.name !== olds.name) body.name = news.name;
      if (news.description !== olds.description) body.description = news.description;
      if (JSON.stringify(news.tags) !== JSON.stringify(olds.tags)) body.tags = news.tags;
      if (news.queriesPerSecond !== olds.queriesPerSecond)
        body.queries_per_second = news.queriesPerSecond;
      if (news.burstSize !== olds.burstSize) body.burst_size = news.burstSize;
      if (news.maxConnections !== olds.maxConnections) body.max_connections = news.maxConnections;
      if (JSON.stringify(news.allowedCidrs) !== JSON.stringify(olds.allowedCidrs))
        body.allowed_cidrs = news.allowedCidrs;
      if (news.status !== olds.status) body.status = news.status;

      if (Object.keys(body).length > 0) {
        await api.projects.updateProject({
          pathParams: { project_id: id },
          body: body as Parameters<typeof api.projects.updateProject>[0]["body"],
        });
      }

      const project = (await api.projects.getProject({
        pathParams: { project_id: id },
      })) as ProjectData;

      return {
        outs: stripUndefined({
          ...projectToState(project),
          database: news.database,
          primaryDatabaseId: olds.primaryDatabaseId as string,
        }),
      };
    } catch (err) {
      if (apiErrorStatus(err) === 404) {
        throw new Error(
          `Project "${String(news.name)}" (${id}) was deleted out-of-band. ` +
            `Run \`pulumi refresh\` to reconcile state, then re-run \`pulumi up\`.`,
        );
      }
      handleApiError("update", "Project", err);
    }
  },

  async delete(id: string) {
    const api = createClient();
    try {
      await api.projects.deleteProject({
        pathParams: { project_id: id },
      });
    } catch (err) {
      // 404 means the resource is already gone — treat as success.
      if (apiErrorStatus(err) === 404) return;
      handleApiError("delete", "Project", err);
    }
  },

  async diff(_id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const replaces: string[] = [];
    if (news.orgId !== olds.orgId) replaces.push("orgId");
    if ((news.cloud ?? "aws") !== (olds.cloud ?? "aws")) replaces.push("cloud");

    const changes =
      news.name !== olds.name ||
      news.description !== olds.description ||
      JSON.stringify(news.tags) !== JSON.stringify(olds.tags) ||
      (news.queriesPerSecond ?? 0) !== (olds.queriesPerSecond ?? 0) ||
      (news.burstSize ?? 0) !== (olds.burstSize ?? 0) ||
      (news.maxConnections ?? 0) !== (olds.maxConnections ?? 0) ||
      JSON.stringify(news.allowedCidrs) !== JSON.stringify(olds.allowedCidrs) ||
      news.status !== olds.status ||
      news.orgId !== olds.orgId ||
      replaces.length > 0;

    return { changes, replaces, deleteBeforeReplace: false };
  },
};

/**
 * Manages a PgBeam project with a primary database.
 */
export class Project extends pulumi.dynamic.Resource {
  /** Better Auth organization ID that owns this project. */
  public readonly orgId!: pulumi.Output<string>;
  /** Human-readable project name. */
  public readonly name!: pulumi.Output<string>;
  /** Optional project description. */
  public readonly description!: pulumi.Output<string | undefined>;
  /** User-defined labels applied to the project. */
  public readonly tags!: pulumi.Output<string[] | undefined>;
  /** Cloud provider where the project runs. */
  public readonly cloud!: pulumi.Output<string | undefined>;
  /** Proxy hostname for connecting through PgBeam (e.g., myproject.aws.pgbeam.app). */
  public readonly proxyHost!: pulumi.Output<string | undefined>;
  /** Maximum queries per second for this project. 0 means unlimited. */
  public readonly queriesPerSecond!: pulumi.Output<number | null>;
  /** Burst allowance above the steady-state rate. 0 uses queries_per_second as burst. */
  public readonly burstSize!: pulumi.Output<number | null>;
  /** Maximum concurrent proxy connections. 0 means unlimited. */
  public readonly maxConnections!: pulumi.Output<number | null>;
  /** IP filtering rules as CIDR ranges with optional labels. When non-empty, only connections from matching IPs are accepted. Empty array means all IPs are allowed (default). Both IPv4 (e.g. 10.0.0.0/8) and IPv6 (e.g. 2001:db8::/32) are supported.
   */
  public readonly allowedCidrs!: pulumi.Output<string[] | undefined>;
  /** Number of databases attached to this project. */
  public readonly databaseCount!: pulumi.Output<number | null>;
  /** Current active connections (latest metrics snapshot). 0 when no metrics data. */
  public readonly activeConnections!: pulumi.Output<number | null>;
  /** Project lifecycle status. */
  public readonly status!: pulumi.Output<string | undefined>;
  /** When the project was created. */
  public readonly createdAt!: pulumi.Output<string | undefined>;
  /** When the project was last updated. */
  public readonly updatedAt!: pulumi.Output<string | undefined>;
  /** Request body for registering an upstream database. */
  public readonly database!: pulumi.Output<ProjectDatabase>;
  /** ID of the primary database created with this project. */
  public readonly primaryDatabaseId!: pulumi.Output<string>;

  constructor(name: string, args: ProjectArgs, opts?: pulumi.CustomResourceOptions) {
    super(
      projectProvider,
      name,
      {
        ...args,
        proxyHost: undefined,
        databaseCount: undefined,
        activeConnections: undefined,
        createdAt: undefined,
        updatedAt: undefined,
        primaryDatabaseId: undefined,
      },
      opts,
    );
  }
}
