// Code generated by generate-pulumi.ts — DO NOT EDIT.

import * as pulumi from "@pulumi/pulumi";
import type { Replica as ReplicaData } from "pgbeam";
import { apiErrorStatus, createClient, handleApiError } from "./provider.js";
import { stripUndefined } from "./utils.js";

export interface ReplicaArgs {
  /** Parent database ID. */
  databaseId: pulumi.Input<string>;
  /** PostgreSQL replica host. */
  host: pulumi.Input<string>;
  /** PostgreSQL replica port. */
  port: pulumi.Input<number>;
  /** PostgreSQL SSL connection mode. */
  sslMode?: pulumi.Input<string>;
}

function replicaToState(r: ReplicaData) {
  return {
    databaseId: r.database_id,
    host: r.host,
    port: r.port,
    sslMode: r.ssl_mode ?? undefined,
    createdAt: r.created_at ?? undefined,
    updatedAt: r.updated_at ?? undefined,
  };
}

const replicaProvider: pulumi.dynamic.ResourceProvider = {
  async create(inputs: Record<string, unknown>) {
    const api = createClient();

    try {
      const result = await api.projects.createReplica({
        pathParams: { database_id: String(inputs.databaseId) },
        body: {
          host: String(inputs.host),
          port: Number(inputs.port),
          ssl_mode: inputs.sslMode as
            | "disable"
            | "allow"
            | "prefer"
            | "require"
            | "verify-ca"
            | "verify-full"
            | undefined,
        },
      });

      const resource = result as ReplicaData;
      return {
        id: resource.id,
        outs: stripUndefined({
          ...replicaToState(resource),
        }),
      };
    } catch (err) {
      handleApiError("create", "Replica", err);
    }
  },

  async read(id: string, props: Record<string, unknown>) {
    const api = createClient();

    try {
      const result = await api.projects.listReplicas({
        pathParams: { database_id: String(props.databaseId) },
      });

      const items = (result as { replicas: ReplicaData[] }).replicas;
      const found = items.find((r) => r.id === id);
      if (!found) {
        throw new Error(`Replica ${id} not found`);
      }

      return {
        id,
        props: stripUndefined({
          ...props,
          ...replicaToState(found),
        }),
      };
    } catch (err) {
      handleApiError("read", "Replica", err);
    }
  },

  async delete(id: string, props: Record<string, unknown>) {
    const api = createClient();
    try {
      await api.projects.deleteReplica({
        pathParams: { database_id: String(props.databaseId), replica_id: id },
      });
    } catch (err) {
      // 404 means the resource is already gone — treat as success.
      if (apiErrorStatus(err) === 404) return;
      handleApiError("delete", "Replica", err);
    }
  },

  async diff(_id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const replaces: string[] = [];
    if (news.databaseId !== olds.databaseId) replaces.push("databaseId");
    if (news.host !== olds.host) replaces.push("host");
    if (news.port !== olds.port) replaces.push("port");
    if ((news.sslMode ?? "disable") !== (olds.sslMode ?? "disable")) replaces.push("sslMode");

    return {
      changes: replaces.length > 0,
      replaces,
      deleteBeforeReplace: true,
    };
  },
};

/**
 * Manages a read replica for a PgBeam database.
 */
export class Replica extends pulumi.dynamic.Resource {
  /** Parent database ID. */
  public readonly databaseId!: pulumi.Output<string>;
  /** PostgreSQL replica host. */
  public readonly host!: pulumi.Output<string>;
  /** PostgreSQL replica port. */
  public readonly port!: pulumi.Output<number>;
  /** PostgreSQL SSL connection mode. */
  public readonly sslMode!: pulumi.Output<string | undefined>;
  /** When the replica was created. */
  public readonly createdAt!: pulumi.Output<string | undefined>;
  /** When the replica was last updated. */
  public readonly updatedAt!: pulumi.Output<string | undefined>;

  constructor(name: string, args: ReplicaArgs, opts?: pulumi.CustomResourceOptions) {
    super(
      replicaProvider,
      name,
      {
        ...args,
        createdAt: undefined,
        updatedAt: undefined,
      },
      opts,
    );
  }
}
