// Code generated by generate-pulumi.ts — DO NOT EDIT.

import * as pulumi from "@pulumi/pulumi";
import type { SelfHostEnrollment as SelfHostEnrollmentData } from "pgbeam";
import { apiErrorStatus, createClient, handleApiError } from "./provider.js";
import { stripUndefined } from "./utils.js";

export interface SelfHostEnrollmentArgs {
  /** Organization that owns this enrollment. */
  orgId: pulumi.Input<string>;
  /** Operator-supplied label for where the proxy runs (informational). */
  regionLabel?: pulumi.Input<string>;
  /** Optional human-readable note. */
  description?: pulumi.Input<string>;
  /** When the enrollment token expires and stops authenticating new proxy connections. Null means it never expires. Enforcement is fail-closed at the gRPC auth gate the instant this time passes. */
  expiresAt?: pulumi.Input<string>;
}

function selfHostEnrollmentToState(r: SelfHostEnrollmentData) {
  return {
    orgId: r.org_id,
    regionLabel: r.region_label ?? undefined,
    description: r.description ?? undefined,
    createdBy: r.created_by ?? undefined,
    createdAt: r.created_at ?? undefined,
    lastSeenAt: r.last_seen_at ?? undefined,
    revokedAt: r.revoked_at ?? undefined,
    expiresAt: r.expires_at ?? undefined,
  };
}

const selfHostEnrollmentProvider: pulumi.dynamic.ResourceProvider = {
  async create(inputs: Record<string, unknown>) {
    const api = createClient();

    try {
      const result = await api.platform.createSelfHostEnrollment({
        pathParams: { org_id: String(inputs.orgId) },
        body: {
          region_label: inputs.regionLabel as string | undefined,
          description: inputs.description as string | undefined,
          expires_at: inputs.expiresAt as string | undefined,
        },
      });

      const resource = (result as { enrollment: SelfHostEnrollmentData }).enrollment;
      const tokenValue = (result as Record<string, unknown>).token as string | undefined;
      return {
        id: resource.id,
        outs: stripUndefined({
          ...selfHostEnrollmentToState(resource),
          token: tokenValue,
        }),
      };
    } catch (err) {
      handleApiError("create", "SelfHostEnrollment", err);
    }
  },

  async read(id: string, props: Record<string, unknown>) {
    const api = createClient();

    try {
      const result = await api.platform.listSelfHostEnrollments({
        pathParams: { org_id: String(props.orgId) },
      });

      const items = (result as { enrollments: SelfHostEnrollmentData[] }).enrollments;
      const found = items.find((r) => r.id === id);
      if (!found) {
        throw new Error(`SelfHostEnrollment ${id} not found`);
      }

      return {
        id,
        props: stripUndefined({
          ...props,
          ...selfHostEnrollmentToState(found),
        }),
      };
    } catch (err) {
      handleApiError("read", "SelfHostEnrollment", err);
    }
  },

  async delete(id: string, props: Record<string, unknown>) {
    const api = createClient();
    try {
      await api.platform.revokeSelfHostEnrollment({
        pathParams: { org_id: String(props.orgId), enrollment_id: id },
      });
    } catch (err) {
      // 404 means the resource is already gone — treat as success.
      if (apiErrorStatus(err) === 404) return;
      handleApiError("delete", "SelfHostEnrollment", err);
    }
  },

  async diff(_id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const replaces: string[] = [];
    if (news.orgId !== olds.orgId) replaces.push("orgId");
    if ((news.regionLabel ?? "") !== (olds.regionLabel ?? "")) replaces.push("regionLabel");
    if ((news.description ?? "") !== (olds.description ?? "")) replaces.push("description");
    if ((news.expiresAt ?? "") !== (olds.expiresAt ?? "")) replaces.push("expiresAt");

    return {
      changes: replaces.length > 0,
      replaces,
      deleteBeforeReplace: true,
    };
  },
};

/**
 * Manages a self-host (BYOC) enrollment: a token a self-hosted proxy uses to authenticate to the control plane's config/audit stream. The token is a one-time secret returned only at creation and exposed as a sensitive computed output; it cannot be retrieved again. To rotate the token, replace the resource. Deletion revokes the enrollment.
 */
export class SelfHostEnrollment extends pulumi.dynamic.Resource {
  /** Organization that owns this enrollment. */
  public readonly orgId!: pulumi.Output<string>;
  /** Operator-supplied label for where the proxy runs (informational). */
  public readonly regionLabel!: pulumi.Output<string | undefined>;
  /** Optional human-readable note. */
  public readonly description!: pulumi.Output<string | undefined>;
  /** User ID that created the enrollment. */
  public readonly createdBy!: pulumi.Output<string | undefined>;
  /** When the enrollment was created. */
  public readonly createdAt!: pulumi.Output<string | undefined>;
  /** Last time a proxy authenticated with this enrollment. */
  public readonly lastSeenAt!: pulumi.Output<string | undefined>;
  /** When the enrollment was revoked. Null means active. */
  public readonly revokedAt!: pulumi.Output<string | undefined>;
  /** When the enrollment token expires and stops authenticating new proxy connections. Null means it never expires. Enforcement is fail-closed at the gRPC auth gate the instant this time passes. */
  public readonly expiresAt!: pulumi.Output<string | undefined>;
  /** One-time enrollment token (pbh_...) for the self-hosted proxy's GRPC_AUTH_TOKEN (shown once). */
  public readonly token!: pulumi.Output<string>;

  constructor(name: string, args: SelfHostEnrollmentArgs, opts?: pulumi.CustomResourceOptions) {
    opts = {
      ...opts,
      additionalSecretOutputs: [...(opts?.additionalSecretOutputs ?? []), "token"],
    };
    super(
      selfHostEnrollmentProvider,
      name,
      {
        ...args,
        createdBy: undefined,
        createdAt: undefined,
        lastSeenAt: undefined,
        revokedAt: undefined,
        token: undefined,
      },
      opts,
    );
  }
}
