// Code generated by generate-pulumi.ts — DO NOT EDIT.

import * as pulumi from "@pulumi/pulumi";
import type { OrganizationPlan } from "pgbeam";
import { apiErrorStatus, createClient, handleApiError } from "./provider.js";
import { stripUndefined } from "./utils.js";

interface Limits {
  queriesPerDay: number;
  maxProjects: number;
  maxDatabases: number;
  maxConnections: number;
  queriesPerSecond: number;
  bytesPerMonth: number;
  maxQueryShapes: number;
  includedSeats: number;
}

export interface SpendLimitArgs {
  /** Organization identifier the plan applies to. */
  orgId: pulumi.Input<string>;
  /** Monthly spend limit in dollars. Null means no limit. */
  spendLimit?: pulumi.Input<number | null>;
}

function spendLimitToState(r: OrganizationPlan) {
  return {
    orgId: r.org_id ?? undefined,
    plan: r.plan ?? undefined,
    billingProvider: r.billing_provider ?? undefined,
    subscriptionStatus: r.subscription_status ?? undefined,
    currentPeriodEnd: r.current_period_end ?? undefined,
    enabled: r.enabled ?? undefined,
    customPricing: r.custom_pricing ?? undefined,
    spendLimit: r.spend_limit ?? null,
    limits: r.limits
      ? {
          queriesPerDay: r.limits.queries_per_day,
          maxProjects: r.limits.max_projects,
          maxDatabases: r.limits.max_databases,
          maxConnections: r.limits.max_connections,
          queriesPerSecond: r.limits.queries_per_second,
          bytesPerMonth: r.limits.bytes_per_month,
          maxQueryShapes: r.limits.max_query_shapes,
          includedSeats: r.limits.included_seats,
        }
      : undefined,
    createdAt: r.created_at ?? undefined,
    updatedAt: r.updated_at ?? undefined,
  };
}

const spendLimitProvider: pulumi.dynamic.ResourceProvider = {
  async create(inputs: Record<string, unknown>) {
    const api = createClient();

    try {
      const result = await api.analytics.updateSpendLimit({
        pathParams: { org_id: String(inputs.orgId) },
        body: {
          spend_limit: inputs.spendLimit as number | null | undefined,
        },
      });

      const plan = result as OrganizationPlan;
      return {
        id: String(inputs.orgId),
        outs: stripUndefined(spendLimitToState(plan)),
      };
    } catch (err) {
      handleApiError("create", "SpendLimit", err);
    }
  },

  async read(id: string, props: Record<string, unknown>) {
    const api = createClient();

    try {
      const resource = (await api.analytics.getOrganizationPlan({
        pathParams: { org_id: String(props.orgId) },
      })) as OrganizationPlan;

      return {
        id,
        props: stripUndefined({
          ...props,
          ...spendLimitToState(resource),
        }),
      };
    } catch (err) {
      handleApiError("read", "SpendLimit", err);
    }
  },

  async update(id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const api = createClient();

    try {
      const result = await api.analytics.updateSpendLimit({
        pathParams: { org_id: id },
        body: {
          spend_limit: news.spendLimit as number | null | undefined,
        },
      });

      const plan = result as OrganizationPlan;
      return {
        outs: stripUndefined(spendLimitToState(plan)),
      };
    } catch (err) {
      const status = apiErrorStatus(err);
      if (status === undefined || status >= 500) {
        const detail = status ? `(${status})` : `(network error)`;
        pulumi.log.warn(
          `PgBeam API unavailable ${detail} during spendLimit update — preserving previous state.`,
        );
        return { outs: stripUndefined({ ...(olds as Record<string, unknown>) }) };
      }
      handleApiError("update", "SpendLimit", err);
    }
  },

  async delete(id: string) {
    const api = createClient();
    try {
      await api.analytics.updateSpendLimit({
        pathParams: {
          org_id: id,
        },
        body: {
          spend_limit: null,
        },
      });
    } catch (err) {
      // 404 means the resource is already gone — treat as success.
      if (apiErrorStatus(err) === 404) return;
      handleApiError("delete", "SpendLimit", err);
    }
  },

  async diff(_id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const replaces: string[] = [];

    const changes = (news.spendLimit ?? 0) !== (olds.spendLimit ?? 0) || replaces.length > 0;

    return { changes, replaces, deleteBeforeReplace: false };
  },
};

/**
 * Manages the monthly spend limit for an organization.
 */
export class SpendLimit extends pulumi.dynamic.Resource {
  /** Organization identifier the plan applies to. */
  public readonly orgId!: pulumi.Output<string | undefined>;
  /** Current plan tier. */
  public readonly plan!: pulumi.Output<string | undefined>;
  /** Which billing provider manages this organization's subscription. */
  public readonly billingProvider!: pulumi.Output<string | undefined>;
  /** Stripe subscription status. */
  public readonly subscriptionStatus!: pulumi.Output<string | undefined>;
  /** End of current billing period. */
  public readonly currentPeriodEnd!: pulumi.Output<string | undefined>;
  /** Whether the organization billing is active (false = suspended). */
  public readonly enabled!: pulumi.Output<boolean | undefined>;
  /** Whether the organization has custom enterprise pricing. */
  public readonly customPricing!: pulumi.Output<boolean | undefined>;
  /** Monthly spend limit in dollars. Null means no limit. */
  public readonly spendLimit!: pulumi.Output<number | null>;
  /** Effective usage limits enforced for an organization plan. */
  public readonly limits!: pulumi.Output<Limits | undefined>;
  /** When the billing record was created. */
  public readonly createdAt!: pulumi.Output<string | undefined>;
  /** When the billing record was last updated. */
  public readonly updatedAt!: pulumi.Output<string | undefined>;

  constructor(name: string, args: SpendLimitArgs, opts?: pulumi.CustomResourceOptions) {
    super(
      spendLimitProvider,
      name,
      {
        ...args,
        orgId: undefined,
        plan: undefined,
        billingProvider: undefined,
        subscriptionStatus: undefined,
        currentPeriodEnd: undefined,
        enabled: undefined,
        customPricing: undefined,
        limits: undefined,
        createdAt: undefined,
        updatedAt: undefined,
      },
      opts,
    );
  }
}
