// Code generated by generate-pulumi.ts — DO NOT EDIT.

import * as pulumi from "@pulumi/pulumi";
import type { WebhookEndpoint as WebhookEndpointData } from "pgbeam";
import { apiErrorStatus, createClient, handleApiError } from "./provider.js";
import { stripUndefined } from "./utils.js";

export interface WebhookEndpointArgs {
  /** Owning project ID. */
  projectId: pulumi.Input<string>;
  /** HTTPS endpoint that receives event deliveries. */
  url: pulumi.Input<string>;
  /** Payload format for delivered events. */
  format?: pulumi.Input<string>;
  /** Event types to deliver. Empty means all events. */
  eventTypes?: pulumi.Input<pulumi.Input<string>[]>;
  /** Whether deliveries are active for this endpoint. */
  enabled?: pulumi.Input<boolean>;
  /** Human-readable label for the endpoint. */
  description?: pulumi.Input<string>;
  /** Shared secret used to sign delivery payloads. Write-only. */
  secret?: pulumi.Input<string>;
}

function webhookEndpointToState(r: WebhookEndpointData) {
  return {
    projectId: r.project_id,
    url: r.url,
    format: r.format ?? undefined,
    eventTypes: r.event_types ?? undefined,
    enabled: r.enabled ?? undefined,
    description: r.description ?? undefined,
    createdAt: r.created_at ?? undefined,
    updatedAt: r.updated_at ?? undefined,
  };
}

const webhookEndpointProvider: pulumi.dynamic.ResourceProvider = {
  async create(inputs: Record<string, unknown>) {
    const api = createClient();

    try {
      const result = await api.webhooks.createWebhookEndpoint({
        pathParams: { project_id: String(inputs.projectId) },
        body: {
          url: String(inputs.url),
          format: inputs.format as "json" | "splunk_hec" | "datadog" | "elastic" | undefined,
          event_types: inputs.eventTypes as string[] | undefined,
          enabled: inputs.enabled as boolean | undefined,
          description: inputs.description as string | undefined,
          secret: inputs.secret as string | undefined,
        },
      });

      const resource = result as WebhookEndpointData;
      return {
        id: resource.id,
        outs: stripUndefined({
          ...webhookEndpointToState(resource),
          secret: inputs.secret,
        }),
      };
    } catch (err) {
      // Adopt orphaned webhookEndpoint on 409 Conflict (e.g. previous create succeeded
      // in the API but Pulumi state was lost due to serialization error).
      if (apiErrorStatus(err) === 409) {
        const url = String(inputs.url);
        const list = (await api.webhooks.listWebhookEndpoints({
          pathParams: { project_id: String(inputs.projectId) },
          queryParams: { page_size: 100 },
        })) as { webhooks: WebhookEndpointData[] };
        const existing = list.webhooks.find((p) => p.url === url);
        if (existing) {
          console.info(`Adopting existing webhookEndpoint "${url}" (${existing.id})`);
          return {
            id: existing.id,
            outs: stripUndefined({
              ...webhookEndpointToState(existing),
            }),
          };
        }
      }
      handleApiError("create", "WebhookEndpoint", err);
    }
  },

  async read(id: string, props: Record<string, unknown>) {
    const api = createClient();

    try {
      const resource = (await api.webhooks.getWebhookEndpoint({
        pathParams: { project_id: String(props.projectId), webhook_id: id },
      })) as WebhookEndpointData;

      return {
        id,
        props: stripUndefined({
          ...props,
          ...webhookEndpointToState(resource),
        }),
      };
    } catch (err) {
      if (apiErrorStatus(err) === 404 && props.url) {
        const list = (await api.webhooks.listWebhookEndpoints({
          pathParams: { project_id: String(props.projectId) },
          queryParams: { page_size: 100 },
        })) as { webhooks: WebhookEndpointData[] };
        const matchName = String(props.url);
        const existing = list.webhooks.find((p) => p.url === matchName);
        if (existing) {
          console.info(
            `Re-adopting webhookEndpoint "${matchName}" (${existing.id}) during read after out-of-band deletion`,
          );
          return {
            id: existing.id,
            props: stripUndefined({
              ...props,
              ...webhookEndpointToState(existing),
            }),
          };
        }
        console.warn(
          `WebhookEndpoint "${matchName}" (${id}) not found during read — it may have been deleted out-of-band.`,
        );
        return { id, props };
      }
      handleApiError("read", "WebhookEndpoint", err);
    }
  },

  async update(id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const api = createClient();

    try {
      const body: Record<string, unknown> = {};
      if (news.url !== olds.url) body.url = news.url;
      if (news.format !== olds.format) body.format = news.format;
      if (JSON.stringify(news.eventTypes) !== JSON.stringify(olds.eventTypes))
        body.event_types = news.eventTypes;
      if (news.enabled !== olds.enabled) body.enabled = news.enabled;
      if (news.description !== olds.description) body.description = news.description;
      if (news.secret !== olds.secret) body.secret = news.secret;

      if (Object.keys(body).length > 0) {
        await api.webhooks.updateWebhookEndpoint({
          pathParams: { project_id: String(news.projectId), webhook_id: id },
          body: body as Parameters<typeof api.webhooks.updateWebhookEndpoint>[0]["body"],
        });
      }

      const resource = (await api.webhooks.getWebhookEndpoint({
        pathParams: { project_id: String(news.projectId), webhook_id: id },
      })) as WebhookEndpointData;

      return {
        outs: stripUndefined({
          ...webhookEndpointToState(resource),
          secret: news.secret,
        }),
      };
    } catch (err) {
      const status = apiErrorStatus(err);
      if (status === undefined || status >= 500) {
        const detail = status ? `(${status})` : `(network error)`;
        console.warn(
          `PgBeam API unavailable ${detail} during webhookEndpoint update — preserving previous state.`,
        );
        return { outs: stripUndefined({ ...(olds as Record<string, unknown>) }) };
      }
      if (apiErrorStatus(err) === 404) {
        throw new Error(
          `WebhookEndpoint "${String(news.url)}" (${id}) was deleted out-of-band. ` +
            `Run \`pulumi refresh\` to reconcile state, then re-run \`pulumi up\`.`,
        );
      }
      handleApiError("update", "WebhookEndpoint", err);
    }
  },

  async delete(id: string, props: Record<string, unknown>) {
    const api = createClient();
    try {
      await api.webhooks.deleteWebhookEndpoint({
        pathParams: { project_id: String(props.projectId), webhook_id: id },
      });
    } catch (err) {
      // 404 means the resource is already gone — treat as success.
      if (apiErrorStatus(err) === 404) return;
      handleApiError("delete", "WebhookEndpoint", err);
    }
  },

  async diff(_id: string, olds: Record<string, unknown>, news: Record<string, unknown>) {
    const replaces: string[] = [];
    if (news.projectId !== olds.projectId) replaces.push("projectId");

    const changes =
      news.url !== olds.url ||
      news.format !== olds.format ||
      JSON.stringify(news.eventTypes) !== JSON.stringify(olds.eventTypes) ||
      news.enabled !== olds.enabled ||
      news.description !== olds.description ||
      news.secret !== olds.secret ||
      news.projectId !== olds.projectId ||
      replaces.length > 0;

    return { changes, replaces, deleteBeforeReplace: false };
  },
};

/**
 * Manages a webhook endpoint that receives project audit and anomaly event deliveries. The signing secret is write-only and never returned by the API.
 */
export class WebhookEndpoint extends pulumi.dynamic.Resource {
  /** Owning project ID. */
  public readonly projectId!: pulumi.Output<string>;
  /** HTTPS endpoint that receives event deliveries. */
  public readonly url!: pulumi.Output<string>;
  /** Payload format for delivered events. */
  public readonly format!: pulumi.Output<string | undefined>;
  /** Event types to deliver. Empty means all events. */
  public readonly eventTypes!: pulumi.Output<string[] | undefined>;
  /** Whether deliveries are active for this endpoint. */
  public readonly enabled!: pulumi.Output<boolean | undefined>;
  /** Human-readable label for the endpoint. */
  public readonly description!: pulumi.Output<string | undefined>;
  /** When the endpoint was created. */
  public readonly createdAt!: pulumi.Output<string | undefined>;
  /** When the endpoint was last updated. */
  public readonly updatedAt!: pulumi.Output<string | undefined>;
  /** Shared secret used to sign delivery payloads. Write-only. */
  public readonly secret!: pulumi.Output<string | undefined>;

  constructor(name: string, args: WebhookEndpointArgs, opts?: pulumi.CustomResourceOptions) {
    opts = {
      ...opts,
      additionalSecretOutputs: [...(opts?.additionalSecretOutputs ?? []), "secret"],
    };
    super(
      webhookEndpointProvider,
      name,
      {
        ...args,
        createdAt: undefined,
        updatedAt: undefined,
      },
      opts,
    );
  }
}
